### ISSUE TITLE
Add ability to query 1 to many relationships

### ISSUE THREAD

**Issue by CodestarGames** [couchbaselabs/node-ottoman#100]
Hello, I'm currently trying to use the query functionality of the models and do what is essentially an inner join between two models. The problem i am having is that when node-ottoman create views for queries, it does it assuming there will only be a 1 to 1 relationship between the models. 

So in terms of the relationship that is on the readme , would need something like this (assuming multiple users could be linked to a post). 

`ottoman.model('Post', {
  users: [ { ref:'User' } ],
  title: 'string',
  body: 'string'
});

ottoman.model('User', {
  name: 'string'
}, {
  queries: {
    myPosts: {
      of: 'Post',
      by: { 'users' : [ { ref: User }  ] }
    }
  }
});`

We would then have to edit the logic in cbstoreadapter at function _buildViewMapFn to be able to tell if we are passing an array of $ref items and make sure to build a foreach loop in the view to emit all the items that match our user. Something like what I have below.

`function(doc, meta) {
  if(doc._type === 'User') {
    doc.Users.forEach(function(item){
    	emit([item["$ref"]], null);
    });
    
    
  }
}`

I would like to know the other devs thoughts on how we could go about implementing this, because we need to be able to have 1 to many relationships in node-ottoman models.

**Comment by brett19** [comment]
Hey @CodestarGames ,
I believe that this is definitely a use-case we should handle.  Keep in mind that using N1QL queries rather than map-reduce will allow you to do this already.  Are you using a version of Couchbase Server which does not allow N1QL queries?
Cheers, Brett

**Comment by CodestarGames** [comment]
I'm using couchbase 4.5, and yes, I could write a n1ql query for this, but since I am using the ODM to get rid of a lot of ad-hoc queries and keep everything model based in the backend, I would prefer it be functionality built into the ODM models.

**Comment by brett19** [comment]
Hey @CodestarGames,
Keep in mind that you can still model this in Ottoman and Ottoman will automatically generate the needed N1QL indexes and queries under the hood for you.
Cheers, Brett

**Comment by CodestarGames** [comment]
I can't model this in ottoman, because lets say I try to use this. 

`ottoman.model('Post', {
users: [ { ref:'User' } ],
title: 'string',
body: 'string'
});

ottoman.model('User', {
name: 'string'
}, {
index: {
findByUser: {
by: 'users'
}
}
});`

It won't work because we have no way of modeling the index to be able to take in an array of referenced Models and create an index by their _id values.

**Comment by brett19** [comment]
Hey @CodestarGames ,
Actually, this is available, off the top of my head, what you are looking for would be something like the following:
```javascript
ottoman.model('Post', {
  users: [ { ref:'User' } ],
  title: 'string',
  body: 'string'
}, {
  index: {
    findByUser: {
      by: 'users[*]'
    }
  }
});
```
or perhaps
```javascript
ottoman.model('User', {
  name: 'string'
}, {
  queries: {
    myPosts: {
      of: 'Post',
      by: 'users[*]'
    }
  }
});
```
Cheers, Brett

**Comment by CodestarGames** [comment]
That doesn't work either, because it tries to generate this map function for the index

`function(doc, meta) {
  if(doc._type === 'Post') {
    emit([doc.users[*].$ref], null);
  }
}`

**Comment by brett19** [comment]
Hey @CodestarGames, I missed a step.  You should use these to force the use of N1QL (although I thought it was default in these cases).

```javascript
ottoman.model('Post', {
  users: [ { ref:'User' } ],
  title: 'string',
  body: 'string'
}, {
  index: {
    findByUser: {
      type: 'n1ql',
      by: 'users[*]'
    }
  }
});
ottoman.model('User', {
  name: 'string'
}, {
  queries: {
    myPosts: {
      type: 'n1ql',
      of: 'Post',
      by: 'users[*]'
    }
  }
});
```

Cheers, Brett

**Comment by CodestarGames** [comment]
I gave that a shot and then n1ql that it generated didn't return me any results

`SELECT META(b).id AS id FROM `default` b WHERE _type='Post' AND `users[*]`.`$ref`='006374b5-9184-45ef-9587-8f50a88a6a28'`

I believe we need to write in some functionality to add an UNNEST statement into the n1ql to properly be able to access the array in the where clause.

**Comment by brett19** [comment]
Hey @CodestarGames, it appears you may not be using the most up to date version of Ottoman.js.  See here for the implementation of array indexing: https://github.com/couchbaselabs/node-ottoman/blob/master/lib/cbstoreadapter.js#L359
Cheers, Brett
