### ISSUE TITLE
remove all documents of the same model

### ISSUE THREAD

**Issue by lan-nguyen91** [couchbaselabs/node-ottoman#104]
Hi,

I want to drop all the *documents* of the same model such as 

```
var Furniture = ottoman.model('Furniture', {
  name: 'string'
});

Furniture.flush or Furniture.drop
```

Is there such feature in ottoman, could you please point me a direction.
If not, would you prefer to build the feature for ottoman.

**Comment by brett19** [comment]
Hey @lan-nguyen91!

We don't actually have any feature like this currently, but it shouldn't be particularly difficult to build it using N1QL under the hood, though we don't have plans for that right away.

Cheers, Brett

**Comment by moxious** [comment]
This would do the job as an N1ql query:

`DELETE FROM yourBucketName WHERE _type='Furniture';`

Using the couchbase driver, you can easily prepare this as a n1ql query and run it.

**Comment by lan-nguyen91** [comment]
thanks @moxious, just in case anyone interest in this feature.

```    
    ... couchbase and ottoman declaration ....

   var N1qlQuery = couchbase.N1qlQuery;

    var query = N1qlQuery.fromString('DELETE FROM ' + ottoman.bucket._name + ' WHERE _type=' + '"' + modelName + '"');

    ottoman.bucket.query(query, function(err, result) {
        if (err) console.error(err);
        console.log(result)
    })
```
