### ISSUE TITLE
Define models in separate project

### ISSUE THREAD

**Issue by jamlen** [couchbaselabs/node-ottoman#106]
I've only just landed onto Ottoman and really like the look of it. I've used Mongoose before and it feels familiar.

My first thought for looking at moving an existing product over to using Ottoman is that I want to be able to define my models in a separate repository (`awesome-app-odm`) and then be able to use those models in the other projects inside this product. (`awesome-app-ui`, `awesome-app-api`, `awesome-app-bookings`)

Is it possible to define them in this way? From looking at #71 I'm guessing it would be difficult.

**Comment by brett19** [comment]
Hey @jamlen,
We designed Ottoman.js such that you are able to define modules which reside in multiple different buckets, this means that the bucket must be assigned before any of the models are defined.  You should be able to define your models in a separate module if you open the bucket connection from there as well.  Perhaps a level of indirection is in order between models and their data-stores to allow the flexibility we have now, while also allowing the models to be defined out of your application.
Cheers, Brett

**Comment by jamlen** [comment]
What about the model is bucket specific? Surely the instance of a model is stored in a given bucket rather than the model itself?

How about something like this instead?

In `awesome-app-odm` (obviously these would be in different files, maybe in different repos, but namespaced):

```js
var ottoman = require('ottoman');
module.exports = {
  hotel: {
    Booking: ottoman.model('Booking', {
      reference: { type: 'string', default: function () { return sid.generate(); }},
      hotelCode: 'string'
    })
  },
  flight: {
    Booking: ottoman.model('Booking', {
      reference: 'string'
    })
  },
  attraction: {
    Booking: ottoman.model('Booking', {
      reference: 'int'
    })
  }
};
```

In `awesome-hotel-booking`:
```js
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');
var odms = require('awesome-app-odm').hotel;
var Booking = odms.Booking;

var booking = new odms.Booking({
  reference: 'talula-123'
}, cluster.openBucket('hotel'));
```

This will still allow me to have models that are specific to a bucket but define them outside the project to get the resuse of the models.

**Comment by moxious** [comment]
If you define indexes on a model (n1ql or refdoc) of course those would have to be stored somewhere, so the moment you mention an index the model has to live somewhere.

In the abstract, if you had no indexes I suppose you could make the case that it doesn't have to have a bucket, but I'm not sure I get the resistance on this point; the entire reason we'd want to use ottoman is to store instances of documents.  To do this, you're always going to be tied to a bucket.   Ottoman's entire purpose/existence is to tie storage of JSON documents to a DB, so if you wanted to do this (except without the DB linkage via a bucket) I'm not sure ottoman would be the go-to tool for that.

Could you expand a bit more on what you mean by reuse of models here though?  What cool thing could you do if not for the requirement that you must specify a bucket?

**Comment by jamlen** [comment]
Now I've thought a bit about it, it does make sense for indexes. The best solution I can come up with is a factory method which you give it your bucket and it will give you back the models.
