### ISSUE TITLE
ensureIndices should not error for 'already exists'.

### ISSUE THREAD

**Issue by brett19** [couchbaselabs/node-ottoman#107]
When calling ensureIndices, the indices it is trying to create already existing should not cause it to error.

**Comment by moxious** [comment]
I have seen this one.  A recent PR I thought addressed this.  It's couchbase 4.5.0 behavior to error when an index already exists

**Comment by moxious** [comment]
See this one https://github.com/couchbaselabs/node-ottoman/pull/99

**Comment by brett19** [comment]
Hmm.  I thought I had cut a release since then, apparently not!  I guess this IS closed!  Cheers @moxious .
