### ISSUE TITLE
ottoman in react-native

### ISSUE THREAD

**Issue by Johnsel** [couchbaselabs/node-ottoman#109]
Hi,

Is it possible to run ottoman on react native? I tried it and I run into quite some dependency issues, I could invest the time to try to get it to run but is it even possible to interface with CB lite?

Thanks!

John

**Comment by Johnsel** [comment]
It seems my question is based on a false premise. It is recommended to interface only with the sync gateway when mobile sync functionality is desired. So my first question would be; can ottoman talk to the sync gateway at all?

**Comment by Johnsel** [comment]
This issue relates to #79.

**Comment by brett19** [comment]
Please track #79.
