### ISSUE TITLE
Ottoman v.1.0.3 fails to create index for model lookup on attribute of related embedded model

### ISSUE THREAD

**Issue by brett19** [couchbaselabs/node-ottoman#113]
Bucket named 'customer360_odm' has been loaded using the import_all.js script, via the models as configured in the attached project. The Customer model is configured to lookup up Customers based on the name attribute of embedded Country models.
The findByCountryName lookup is exposed, and works correctly as used in this following route of the app.js file in the project:
app.get('/customers/country/:name', function(request, response) {
// + Verify customer360_odm bucket is loaded with documents where Country is embedded in Customer
// Create findByCountryName method on Customer model
// Use name parameter from GET request to retrieve all Customers by the name of their (embedded) Country
var countryName = request.params.name;
models.Customer.findByCountryName(countryName, function(err, customers){
if (err) {
response.status(404).json(
{'error': err}
);
} else if (customers.length == 0) {
response.status(200).json(
{'status': 'No document matched ' + countryName}
);
} else
{ response.status(200).json(customers); }
});
});
However, no corresponding N1QL index appears to be created in Couchbase, though the other lookup defined in the example code (findByCountryCode) does cause a corresponding index to be created.
Because the primary index is automatically verified and created at startup by .ensureIndices(), I am unable to drop the primary index to determine whether this would break the lookup, as I'd expect, for lack of any index at all.
All assets needed to replicate this issue are in the attached archive, including the data needed to load the bucket.

Created from: https://issues.couchbase.com/browse/JSCBC-325

**Comment by gsi-alejandro** [comment]
This use case works fine in Ottoman v2.

The below code works as expected

```
const SchemaCountry = new Schema({name: String})

const Userschema = new Schema({
  'billingAddress': {
    'country': SchemaCountry,
  },
});
Userschema.index.findByCountryName = {
  by: 'billingAddress.country.name',
  type: 'n1ql'
}
```

Notice: Now you have to use Schema
