### ISSUE TITLE
Promises instead of callbacks

### ISSUE THREAD

**Issue by matheusrocha89** [couchbaselabs/node-ottoman#115]
I saw that the ottoman uses callback functions, sometimes it's not very "elegant" to use, handle and maintain the code. Maybe implements Promises on it would be better.

**Comment by matheusrocha89** [comment]
@nraboy

**Comment by moxious** [comment]
There is a pattern used by other libraries "Promisify" using Bluebird where you can make all methods do both easily.

Say you have:

```
function foo(args, callback) {
    callback(5);
}
```

You can change that to this:

```
function foo(args, callback) {
    return new Promise((resolve, reject) => {
        return resolve(5);
    }).nodeify(callback);
}
```

This function behaves in the legacy way (calls callback as expected), doesn't change the function argument types, and returns a promise.  So it could retain the existing callback API and allow promises to be returned.

Most ottoman functions either don't return, or return something useless like null/undefined.

It's an idea for a PR I've had to do this pattern for at least the public API of ottoman, haven't gotten to it yet.

**Comment by matheusrocha89** [comment]
@MorrieSchreibman

**Comment by matheusrocha89** [comment]
Clicked wrong, sorry 😄  @moxious I think it's a great idea. We can both work on it, what do you think?

**Comment by moxious** [comment]
I'd support this idea, but I'm not the maintainer and I can't prioritize this right at the moment because of so much else that is happening.

**Comment by matheusrocha89** [comment]
👍  I undestand.

**Comment by lan-nguyen91** [comment]
I love this feature and tcheever PR, using promise we can incorporate `yield and await` from ES6. Any ETA that this will happen, right now i'm using promissifyAll from bluebird as a work around, but I find adding Async keyword is not a pretty solution after all.

**Comment by amalahussein** [comment]
+1 on this feature -- I'm using Koa2 and the callbacks here ruin the 'sync' like 'async' flow. 

Any idea where this feature is currently on the roadmap, and is there anything we can do to pitch in?

**Comment by AV25242** [comment]
Ottoman V2 fully supports Promise
