### ISSUE TITLE
Reference document doesn't populate data

### ISSUE THREAD

**Issue by lan-nguyen91** [couchbaselabs/node-ottoman#121]
```
var color = ottoman.model('Color', {
  value : {
    type : "string"
  }
})

var Furniture = ottoman.model('Fur', { 
   type: { type: 'string' },
   color : { ref : 'Color' }
 }
)

var c = new color({ value : "777777" });

c.save(function(err, doc){
  if(!err) {

    var test = new Furniture({
      type : 'couch',
      color : c
    })

    test.save(function(err, doc){
      console.log(test);
    })
  }
})

Furniture.find({}, function(err, doc){
  console.log('doc', doc[0].color);
})
```

the first logging show the color `console.log(test);` as // { value : 77777 }
```
OttomanModel(`Fur`, loaded, key:Fur|6ace0a3e-9465-4c26-a699-6ba6a7b1a995, {
  _id: '6ace0a3e-9465-4c26-a699-6ba6a7b1a995',
  type: 'couch',
  color: OttomanModel(`Color`, loaded, key:Color|64f8ac67-a334-4cf6-aa59-67c16a2cf3e2, {
    _id: '64f8ac67-a334-4cf6-aa59-67c16a2cf3e2',
    value: '777777',
  }),
})
```

the second logging `console.log('doc', doc[0].color);` show the color object but no data show up
``` 
    _id: '2ccf7aee-9f3e-45d0-b6da-fa003ab405ab',
    type: 'couch',
    color: OttomanModel(`Color`, unloaded, key:Color|0d4b1f7b-e4d9-4ee2-bc31-67c208d23b89, {}),
```

I notice the first call the color model is loaded, but i don't understand why it is not loaded when using find.

**Comment by moxious** [comment]
In your first example, you're setting the reference to an actual model instance.   References are compatible with model instances, so you're doing it fine there.  When you console.log it, of course you see the whole model, that's what you set it.

The second time, you're printing what you loaded from the DB.  In ottoman references can be loaded or unloaded.  The ones saved to the DB are always unloaded by default.  This is a very, very good thing for several reasons:

1. If ottoman saved the full model and not a reference, you wouldn't get updated if the referred model changed
2. The referred model may have different security parameters you'd want to enforce separately.
3. In the case of circular models (A -> B -> A) which are of course possible, pre-loading all references would cause infinite recursion, kaboom.

So the rule of thumb is that when you get a reference from the db, it's in "unloaded" state.

Want the data?  That's easy, just call the load() function on the reference (color in your second example) and you'll get the full model instance like you had in your first example.

HTH

**Comment by brett19** [comment]
Just to add to @moxious's answer.  You can actually implicit load more of the submodels through various tools.  You can pass the 'load' option to `.find` to specify specific paths to load (ie: `.find({}, {load: ['color']})`.  You can also pass the 'depth' option to load all models up to a certain depth.

P.S. @moxious, recursive loading is supported.  A->B->A will make B's reference to A point to the actual model instance it already loaded as part of that `.load` call.

Cheers, Brett

**Comment by lan-nguyen91** [comment]
Woa this is nice, yes @moxious load() works fine, i understand now, this is actually a very neat feature. thanks guy.

**Comment by rikantro** [comment]
the load options not works,

I have this

```
menu.find({},{load: ["Process", "Item"]},  (error, result) => {
     if(error)
         console.log(error);

     else
         console.log(result);
 });
```

and the error stack :

Error: Invalid type specified (Item)
    at _decodeValue (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:430:13)
    at _decodeValue (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:471:21)
    at _decodeFields (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:506:16)
    at Schema.applyDataToObject (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:604:3)
    at Function.ModelInstance.applyData (C:\testing\couchbase\node_modules\ottoman\lib\modelinstance.js:84:12)
    at C:\testing\couchbase\node_modules\ottoman\lib\modelinstance.js:585:23
    at C:\testing\couchbase\node_modules\ottoman\lib\cbstoreadapter.js:77:5

I'm using the last version at the moment (ottoman 1.0.4) 
The content of the only document is :

```
{
  "_type": "Menu",
  "menuID": "eccfffff-15a8-459e-a8c3-c2ec7d937768",
  "items": [
    {
      "_type": "Item",
      "$ref": "70df4792-5e3d-4c42-90e7-d44b4f65ced0"
    },
    {
      "_type": "Item",
      "$ref": "cc2a7a4b-a6de-4259-b196-73793146038e"
    }
  ],
  "createdAt": "2016-10-19T23:06:12.761Z",
  "proces": {
    "_type": "Process",
    "$ref": "dea1c7f7-d8d0-42fb-afa6-8b10bbb919f1"
  }
}
```

I trying to  use the getById method, the error is the same.

**Comment by brett19** [comment]
Hey @rikantro,
You should be specifying the field path rather than the document type in the `load` option.
Cheers, Brett

**Comment by rikantro** [comment]
Thanks @brett19  it works as 

```
 menu.find({},{load: ["process", "items"]},  (error, result) => {
     if(error)
         console.log('hay error: ' + error);

     else
         console.log(result);
 });
```

but only works if preload first the document types of  the properties (Process and Item Models).
If dont do the preload step, the same error appears again

```
Error: Invalid type specified (Item)
    at _decodeValue (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:430:13)
    at _decodeValue (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:471:21)
    at _decodeFields (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:506:16)
    at Schema.applyDataToObject (C:\testing\couchbase\node_modules\ottoman\lib\schema.js:604:3)
    at Function.ModelInstance.applyData (C:\testing\couchbase\node_modules\ottoman\lib\modelinstance.js:84:12)
    at C:\testing\couchbase\node_modules\ottoman\lib\modelinstance.js:585:23
    at C:\testing\couchbase\node_modules\ottoman\lib\cbstoreadapter.js:77:5
```

How can get the data without preload the referenced models ?

**Comment by brett19** [comment]
Hey,
Can you elaborate on what you mean 'preload step'?
Cheers, Brett

**Comment by rikantro** [comment]
Yes, I was thinking that with the load option, ottoman load the definitions of the models from some place, but i reviewed the code and I see my mistake.
