### ISSUE TITLE
Support for "Unique" document property 

### ISSUE THREAD

**Issue by pkpbytes** [couchbaselabs/node-ottoman#125]
How to define a custom unique field for a document ?
like
ottoman.model('User', {
    username: { type: 'string' , **unique**: true}, .....});

**Comment by ChopperLee2011** [comment]
as I known, Couchbase does not support to defined a unique constraint, maybe u can use "lookup document" for this demand.

**Comment by brett19** [comment]
Currently, the only way to enforce atomic uniqueness would be to use your unique field as the key for the document.

Cheers, Brett

**Comment by DanlanNZ** [comment]
this may be achievable with a validator, but would require validators to accept callbacks as a parameter, something like this. (disclaimer: I haven't tried it)
```javascript 
function UniqueUsernameValidator(val, callback) {
  this.find({ username: val }, (err, usernames) => {
    if (err) return callback(err);
    if (usernames.length) return callback(null, false)
    return callback(null, true);
  });
}

ottoman.model('User', {
  username: { type: 'string' , validator: UniqueUsernameValidator.bind(this)}, .....});
});
```

**Comment by DanlanNZ** [comment]
a standard type of `key: { type: 'uuid' }` would be nice but could also be achieved with a validator function. probably not too relevant for your use case @pkpbytes

@brett19 would an additional standard type for uuid be considered for contribution?

**Comment by moxious** [comment]
It would be possible with a validator, but I wouldn't recommend it.  You wouldn't necessarily have to have a callback, you could do a deasync trick to make the caller of the validator work without having a callback.

But aside from whether this is possible, the downside is that if any of your validators do database access logic, you make it hard to predict how long things will take.  The amount of time it takes to save a new record now starts to depend on how many other records of its type you have, how long this find takes, whether you've got the right indexing set up, etc -- so I think it's not the right approach.

It's possible ottoman could do this another way, there are refdoc indexes, which use a key/value in couchbase to store a lookup key for a particular field/value combination.  Those could probably be reused to enforce uniqueness in some way.   E.g. if you have a refdoc index on a field "username", each time there's a new value, a K/V is put into couchbase.  If a new value comes in, now all you have to do is check if the refdoc field is already in the DB.  If it is, you know the newly inserted value isn't going to be unique, and you reject.

This could also be done by a validator but it's messy, this is better to be done in ottoman itself, IMHO.

**Comment by DanlanNZ** [comment]
> better to be done in ottoman itself

@moxious agreed :+1: was thinking validators as a quick workaround

**Comment by pkpbytes** [comment]
Thank u guys for help... 

@moxious Thats what ended up doing using https://www.npmjs.com/package/couchnode ... almost


var db =  new couchbase.Cluster().openBucket(...
Airport.prototype.save = function(cb) {
    var err = this.invalid();
    if (err) {
        return cb(err);
    }
    db.get("airport:name:" + this.name, function(err, res) {
        if (!err) {
            console.log('error : key exists airport:name');
            return cb({
                error: 'name not unique'
            });
        }
    });
    this.uid = uuid.v4();
    var that = this;
    db.insert(that.uid, that, function(err, res) {
        if (err) {
            return cb(err);
        } else {
            // console.log('that : ', that);
            db.insert("airport:name:" + that.name, that.uid, function(err, res) {
                if (err) {
                    console.log('error : ', err);
                    return cb(err);
                } else {
                    return cb(null, that);
                }
            });

        }
    });
};
