### ISSUE TITLE
Null dates get applied incorrectly by model instance

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#127]
This line of code here:

https://github.com/couchbaselabs/node-ottoman/blob/master/lib/schema.js#L471

When you create a model, and then apply data to it, like this:

```
var model = ottoman.model('Foo', { x: { type: 'Date', default: null } });
var myInstance = new model({ x: null });
```

The code linked above interferes, it creates a `new Date(input)`, which according to javascript dates, if you provide null results in `Thu Jan 1 1970 00:00:00`.  This is incorrect because date fields can't seem to hold null, and also because if a user specifies null, they get the beginning of the epoch instead.

**Comment by brett19** [comment]
Hey @moxious,
It seems reasonable to special-case the DateTime Core Type so that null and undefined do not get directly passed in to the method.  Though this might be strange, since then it would not be possible to create a Date object based on 'default construction' anymore.
Cheers, Brett

**Comment by moxious** [comment]
That's why I submitted it here rather than just putting in a PR, correct behavior is not clear to me.  Dates should be able to be null; the default of 1970 is not likely to ever be useful, but if a user passes some value via a construction object, it should get used.   Default construction seems like it's the right thing to do, except if the value is undefined/null.

Even despite this, default construction shouldn't apply if the model has a "default" field there.  E.g. I don't see any argument why the model above would have the value 1970 in it, since it specified default: null.

**Comment by brett19** [comment]
This will be a breaking change, but I suspect that null being passed directly rather than being generated as `new Date(null)` would likely be acceptable behaviour.  If anyone wants the specific behaviour of having a default date object, they could simply use `default: Date` or use a custom function for it.

**Comment by moxious** [comment]
@brett19 so, would you be open to a PR that does this, or are you scheduling it as part of another batch because it's a breaking change?  Fixing this and testing it should be straightforward.  In the meantime, I'm seeing some rather serious downstream consequences of this.   A model which has a date field backed by ottoman, say when you get to front-end development, has the consequence that the date field must be populated or the model can't be saved, i.e. impossible to have optional date fields.   I'm at the point where I either have to put in some ugly front-end hacks (kick the date out to an unrealistic extreme, and then display it as blank to the user if it's in some range) or I need to get this fixed in order to have optional dates on a front-end backed by ottoman.

**Comment by moxious** [comment]
I've put in a  PR -- we really need this one fixed, as it's creating other bugs for us.

**Comment by brett19** [comment]
I am going to try to gather up a few breaking changes and do them all at once.

**Comment by gsi-alejandro** [comment]
In Ottoman v2 it works as @moxious expect in the issue description.

myIntance.x === null
