### ISSUE TITLE
Implement Bucket Closing

### ISSUE THREAD

**Issue by kivervinicius** [couchbaselabs/node-ottoman#128]
I need to close the bucket after using it? what is the best practice for and finalize a bucket using the ottoman

**Comment by brett19** [comment]
Hey @kivervinicius,

There is not currently a method to close a bucket directly from the ottoman object.  Your best bet is to fetch the StoreAdapter that is being used and close it from there.

```javascript
ottoman.store.bucket.close();
```

Cheers, Brett

**Comment by kivervinicius** [comment]
Hello, thank you for rapid response, currently the best way to work with ottoman, it keeps always open connection? As you exhale is requested a new automatically?

**Comment by brett19** [comment]
Hey @kivervinicius,
It is definitely suggested that you keep a connection open as long as your application is running and may perform requests.  Connecting anew requires a disproportional amount of time compared to an operation, and there is barely a cost to maintaining the connection.
Cheers, Brett

**Comment by kivervinicius** [comment]
Oh, tks @brett19.
