### ISSUE TITLE
Fix Multi-Bucket Indexing

### ISSUE THREAD

**Issue by brett19** [couchbaselabs/node-ottoman#131]
Ottoman is designed to allow you to specify a specific storage adapter on each model.  There is currently a bug however where the models create their index data on a specific bucket, which rather than tracking the models internal storage adapter, uses the one on the top-level Ottoman object.  This means that indexing on multiple buckets is broken.  See #77 for more details.

**Comment by gsi-alejandro** [comment]
In Ottoman v2 it can be solved by using multiple connections.
