### ISSUE TITLE
<static> pre(event, handler) not working

### ISSUE THREAD

**Issue by justic3** [couchbaselabs/node-ottoman#136]
I am trying to hash to password before saving to the db however it keep showing up 
TypeError: next is not a function

UserModel.pre("save", function(next) {
    this.password = hash("test");
    console.log(util.inspect(next, false, null))

```
next();
```

});

**Comment by DanlanNZ** [comment]
the next callback should be the second argument for the Model.pre callback if that makes sense

something like this:
```javascript
UserModel.pre('save', function (user, next) {
  this.password = hash("test");
  next();
});
```

**Comment by moxious** [comment]
Pre handlers should be executed with the arguments (modelinstance, next callback) just as you say.   Code that does that is right here: https://github.com/couchbaselabs/node-ottoman/blob/master/lib/schema.js#L663
