### ISSUE TITLE
storage of embeded models

### ISSUE THREAD

**Issue by danlannz** [couchbaselabs/node-ottoman#137]
from [this](http://blog.couchbase.com/nodejs-odm-couchbase-ottoman) blog post I became aware the embedding Models inside each other is possible like so

``` javascript
var User = Ottoman.model('User', {
  location: { ref: 'GPSPosition' },
});

var GPSPosition = Ottoman.model('GPSPosition', {
  lat: 'number',
  long: 'number'
}, {
  embed: true
});
```

I am currently using this feature on a project but I'm unsure how it is implemented as I can't see any reference to the keyword embed in the codebase. I would have expected it to be implemented in [this function](https://github.com/couchbaselabs/node-ottoman/blob/master/lib/ottoman.js#L681) 

@brett19 @moxious could you enlighten me?

I guess my real question is, are embedded documents able to be stored separately outside of a parent model and if so, are they kept in sync or would that be left up to the application to manage

**Comment by moxious** [comment]
There isn't an embed keyword that I'm aware of, it would be `ref` instead, and that is implemented.

I use a lot of references in my models, but I don't try to embed other documents.  References in ottoman are typically stored in the DB in an unloaded state, so really they're just a pointer to the other document.  If it gets deleted or the other document changes, then the reference is impacted.

A potential gotcha with references is if you assign a model into a reference, that will work, but what gets saved in the DB is just the pointer, not the full document.

If you embed an actual document into another one, it won't be auto-updated by any framework really, this is a kind of denormalization I would recommend you not do unless you have a serious performance reason why you must, and in those cases it would be your responsibility to keep the document up to date.

We do use something we think of as "schema snippets" which are reusable model components.  I.e. a subdocument for storing an address structure.   In that case though it's more of a copy/paste convenience, not really an embedded document.

**Comment by DanlanNZ** [comment]
thanks @moxious, yes it was those schema snippets I was referring to. I have come to realise I was defining the child within the parent object using `key: { type: 'EmbeddedType' }` instead of a reference and the `embed: true` option was completely redundant

I completely agree re. avoiding unnecessary denormalization and I'm only pursuing it as the data is required by the Sync Gateway sync function in order to configure document access correctly

**Comment by gsi-alejandro** [comment]
Ottoman v2 support both types Embed and References documents, please see the [docs](https://v2.ottomanjs.com/guides/schema.html#allowed-schematypes-are)

use Embed to work with subdocuments
use Reference to work in a relational fashion, saving just the document id for later reference the entire document if needed.
