### ISSUE TITLE
Type with the name User was already registered

### ISSUE THREAD

**Issue by dancet** [couchbaselabs/node-ottoman#14]
I'm running your example, saving data to CB. Works fine first time, but when I hit my endpoint for a second time I see "Type with the name User was already registered".

I see in your code you're maintaining a typeList array, and the code is checking for duplicates and throwing this error. Which makes me fairly sure I'm using the library incorrectly. Can you provide some further insight into the correct usage beyond the basic example provided?

**Comment by brett19** [comment]
I know this is very delayed.  In your case I suspect you are calling Ottoman.model within your endpoint instead of once at the startup of your application.  The models only need to be registered once, and you can use them multiple times following that!
