### ISSUE TITLE
Model References cannot be made optional

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#149]
I'm seeing that when you create a model ref inside of a model, you cannot use a null value for instance data there, otherwise you get this error:

```
Error: Expected value to be a ModelInstance of type `User`.
```

Why is this?  Granted, null isn't an instance of a User model, so the error makes sense, but this has the consequence that model instances are always required fields, and cannot be optional.   This clashes with other aspects of ottoman, like the ability to specify `default: null`.

Linking it to the other issue with dates that was reported (https://github.com/couchbaselabs/node-ottoman/issues/127) the common thread is non-handling of null values, and disregard for the `default` setting.

**Comment by moxious** [comment]
Following up on the other issue, there's another similar consequence about inability to "unset" a value.   Suppose I have a model, and I include a reference to a user.  I set that to some value.  Because null cannot be a valid model reference value, that particular ref field may never be removed / updated except to another valid reference.

**Comment by brett19** [comment]
This is definitely an error, and one that should be relatively trivial to correct.

**Comment by moxious** [comment]
If you like I can roll it into my other PR which basically does the same thing but for dates?

**Comment by brett19** [comment]
That would be alright.  Keep in mind that 'undefined' and 'null' should have differing semantics.  'undefined' should trigger 'default', and 'null' should be truly null.

**Comment by gsi-alejandro** [comment]
Schema reference could be optional in Ottoman v2.
