### ISSUE TITLE
Default value support

### ISSUE THREAD

**Issue by majimboo** [couchbaselabs/node-ottoman#15]
Is there a support for default values? Is this project still alive?

**Comment by brett19** [comment]
Hey majimboo, the project is indeed still alive, it was just on hiatus for a period of time to work on some other projects.  We are back in action though, and default values have been implemented and will be available in our 0.1 release!

**Comment by brett19** [comment]
fa048f6dbff1e2e29b24686fb8e96b7a6aa3729e
