### ISSUE TITLE
Add $in keyword to find for querying with arrays

### ISSUE THREAD

**Issue by renelux** [couchbaselabs/node-ottoman#150]
Please add the $in keyword to the .find method so that we can query with array values.

Example:
`User.find({email: {'$in': ["example@example.com", "example2@example.com"]}});`

For more info see: https://forums.couchbase.com/t/ottoman-find-where-value-is-in-array/10979

**Comment by kunalmaity** [comment]
@brett19 I also need ``` $in ``` to be worked with Ottoman for my development. So will it work now please let me know.

**Comment by kunalmaity** [comment]
@renelux 

   You can use below enhancement version of @brett19 original package.

   https://www.npmjs.com/package/ottoman-in

**Comment by AV25242** [comment]
@gsi-alejandro  for now can you verify if this functionality exist in Ottoman V2. From the comments there seems to be functionality thats was made available [here](https://www.npmjs.com/package/ottoman-in)  not sure if that was ported over.

same for not in $nin if neither of these exists let me know I will open a new ticket for review

**Comment by gsi-alejandro** [comment]
Yes, both functionalities exist by using the query builder.

{$in: {....}}
$not: {$in: {....}}

Ottoman v2 provides a very powerful query builder, please check this link for more information https://v2.ottomanjs.com/guides/query-builder.html

Notice: $nin operator doesn't exists but can be achieve by combining $not and $in operators $not: {$in: {....}}).

**Comment by rajasekar-mu** [comment]
Hi ,

How we execute $in operations, below one is correct?

let params = {where: {$in: { search_expr: 'id', target_expr: ["a3827bf5-ea3f-4c56-ae8d-542b23e77213", "155f1772-c671-4703-8bdc-d379d4c4ba47"] }} }
const query = new Query(params, 'StoresPPE').select([{ $field: 'name' }]).limit(10).build();

or any other way
