### ISSUE TITLE
change indicies to indexes in v2

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/node-ottoman#151]
Since you're looking at v2…

I think indexes is a much more common term and more correct than indicies, which fails in most spell checkers.  The ensureIndicies() always bothered my eyes a bit.

**Comment by ingenthr** [comment]
Well, maybe I'm wrong:
http://grammarist.com/usage/indexes-indices/

Up to you!

**Comment by brett19** [comment]
I will do this, and include a backwards compatibility `ensureIndices` method forward.

**Comment by gsi-alejandro** [comment]
Ottoman v2 uses the term `indexes`, due to it's more common term as @ingenthr mention above, thank you a lot.

Feel free to open new tickets, we'll address them ASAP.

Cheers.
