### ISSUE TITLE
CRUD - operations options

### ISSUE THREAD

**Issue by apapacy** [couchbaselabs/node-ottoman#152]
I need to specify options in the CRUD operations. For example {persist_to: ...}. Then consecutive operations: save, find will give the expected results

https://github.com/couchbaselabs/node-ottoman/blob/master/lib/cbstoreadapter.js#LC107
```
  if (cas) {
    this.bucket.replace(key, data, { cas: cas , +++++++++}, saveHandler);
  } else {
    this.bucket.insert(key, data, {+++++++++++++}, saveHandler);
}
```

**Comment by brett19** [comment]
Hey,
Are you using views or N1QL.  If you are using N1QL, GSI indexes data directly from the KV nodes, so specifying a consistency level above 'NONE' should behave as you expect, without needing to specify persistence/replication constraints.  I am however going to look into providing those two specific knobs through the ottoman API.
Cheers, Brett

**Comment by apapacy** [comment]
I am use N1QL for retrive ref documents/ For example

`ottoman.bucket.query, N1qlQuery.fromString("select p.body, p.title, u.name from default p  join default u on keys 'User|' || p.`user`.`$ref`  where u._type='User' and p._type='Post' order by u._id desc  limit 10 offset 0"))`

**Comment by brett19** [comment]
Hey @apapacy,

If you use N1qlQuery.Consistency.REQUEST_PLUS consistency on that N1QL query, you will see any changes that you had made before the query was executed.  Regardless of whether it has been replicated or persisted yet (assuming no cluster topology changes happen in between, such as rebalances or failovers).

Cheers, Brett

**Comment by apapacy** [comment]
N1qlQuery.Consistency.REQUEST_PLUS solved the problem. Thank you
