### ISSUE TITLE
Compound N1QL Indexes do not get created

### ISSUE THREAD

**Issue by jamespdlynn** [couchbaselabs/node-ottoman#153]
Currently if you try to create a N1QL index with more than one field the following error is thrown by Couchbase: **Unhandled rejection Error: GSI CreateIndex() - cause: Invalid index name**
This appears to be due to invalid "$" delimiter characters in the index name.

This error only appears to be thrown in Couchbase 4.5+. In Couchbase 4.1 the error doesn't get thrown but the indexes are not created regardless.

**Comment by gsi-alejandro** [comment]
Hi @jamespdlynn 

Ottoman v2 support compound n1ql Indexes.

please try it. https://v2.ottomanjs.com

Cheers
