### ISSUE TITLE
Update to version 2.2.5

### ISSUE THREAD

**Issue by goatandsheep** [couchbaselabs/node-ottoman#155]
We should update the npm couchbase dependency to version 2.2.5 from 2.2.2

What would it take? If not much, I'll write a pull request.

**Comment by brett19** [comment]
It should be as simple as updating the package.json.  Some minor testing should be performed as part of that though.  Circle-CI should handle most of it I think.

**Comment by goatandsheep** [comment]
Alright I made the change here: https://github.com/couchbaselabs/node-ottoman/pull/157
