### ISSUE TITLE
Failure to properly escape bucket names in index creation.

### ISSUE THREAD

**Issue by jmn8718** [couchbaselabs/node-ottoman#158]
When i run `ottoman.ensureIndices` i get the following error
```
failed to created neccessary indices { Error: syntax error - at -
    at /home/motoko/workspace/heroku/couchbase-api/node_modules/couchbase/lib/bucket.js:668:15
  requestID: '5f8eeace-586c-4e4a-8e95-69e7fb1055d8',
  code: 3000,
  otherErrors: [] }
```

**Comment by kivervinicius** [comment]
I'm have same problem

**Comment by enlore** [comment]
I had a similar issue. I had named my bucket `bucket-name` with a hyphen. If you're creating n1ql indexes, n1ql is going to throw because the hyphen is a reserved character. I corrected this issue by renaming my bucket `bucket_name`.

**Comment by jmn8718** [comment]
Changing the bucket name solved my problem

**Comment by gsi-alejandro** [comment]
@brett19 Ottoman v2 will bubble up the error thrown by couchbase SDK 3. Is needed something else?

**Comment by AV25242** [comment]
@gsi-alejandro if use a bucket name with travel-sample inside ticks will that work ?  something like `travel-sample`

**Comment by gsi-alejandro** [comment]
@AV25242 Ottoman v2 will work fine with `travel-sample`; bucket names with hyphen and indexes will be created successfully.
I thought it's was supported by Server or SDK at some time in the past. Now is working ok, I run some test to ensure it.
