### ISSUE TITLE
ottoman vs couchbase version confusion

### ISSUE THREAD

**Issue by 1tylermitchell** [couchbaselabs/node-ottoman#159]
In my package.json I'm using:

```
  "dependencies": {
    "express": "*",
    "couchbase": "*",
    "body-parser": "*",
    "ottoman":"*"
  },
```

But app complains about mismatched versions or something similar?  Is this truly a version mismatch or something else deeper in my app (bikeshop-cb)?

```
throw new Error('The couchbase module version used by the application'
      ^

Error: The couchbase module version used by the application does not match Ottomans.  Please explicitly pass the application couchbase module using `StoreAdapter.Couchbase`.
```

**Comment by locnguyen** [comment]
If you remove `couchbase` from your dependencies list, clean out `node_modules/` and `npm install` do you still see the same error?

**Comment by allyssonv** [comment]
Hi, @1tylermitchell 

I have in trouble with the same error. Did you get a solution for this?

**Comment by CanRau** [comment]
for me removing couchbase completely, inserting this in package.json dependencies
`"couchbase": "~2.2.2"`
and yarn install / npm install
did the trick :)
actually I removed and installed multiple times (ottoman, too) until it finally worked ^^

**Comment by hashbangdev1** [comment]
I've tried multiple versions of the couchbase and ottoman dependencies in package.json and I'm getting the same error. Using node v8.0.0.

Any ideas?

**Comment by CanRau** [comment]
Eventually I dropped ottoman for more control using custom lookup documents and n1ql, running newest node sdk 2.3.4

**Comment by brett19** [comment]
Hey @hashbangdev1 ,
What version of ottoman and Couchbase are you using, and what error are you getting?  Have you tried comparing the ottoman package json version to yours?
Cheers, Brett

**Comment by hashbangdev1** [comment]
Hi @brett19 

App's package.json:

`  "dependencies": {
    "body-parser": "^1.14.2",
    "couchbase": "~2.3.0",
    "express": "^4.13.3",
    "ottoman": "^1.0.4"
  }`

Ottoman's package.json:

`  "dependencies": {
    "bluebird": "^3.4.1",
    "couchbase": "~2.3.0",
    "jsonpath": "~0.2.2",
    "lodash": "^4.15.0",
    "lodash-deep": "^2.0.0",
    "uuid": "~2.0.1"
  }`

and the error:

`throw new Error('The couchbase module version used by the application'`

`Error: The couchbase module version used by the application does not match Ottomans.  Please explicitly pass the application couchbase module using `StoreAdapter.Couchbase`.`

Thanks

**Comment by hashbangdev1** [comment]
Without re-installing any dependencies, this seemed to have worked:

`let myCluster = new couchbase.Cluster(config.couchbase.server, (err) => {
 if (err) {
   console.log("Can’t connect to couchbase:", err);
 }
 console.log("connected");
});

let myBucket = myCluster.openBucket("mobile_bucket", "abc123", (err) => {
 if (err) {
   console.log("Can’t connect to bucket:", err);
 }
 console.log("connected to bucket");
});

ottoman.store = new ottoman.CbStoreAdapter(myBucket, couchbase);`

After doing that, I was able to instantiate models and run:

> ottoman.ensureIndices(function(err) {
>  if (err) {
>    return console.error("Error ensure indices USER", err);
>  }
>  console.log("Ensure indices USER");
> });

I also never knew that there was a default password created for a bucket and I found this with:
curl -u AdminUser:adminPassword http://localhost:8091/pools/default/buckets

Hope that helps someone.

**Comment by waffledonkey** [comment]
try force installing couchbase@2.2.5; `npm install --save couchbase@2.2.5`.  They bumped `package.json` to `2.3.x`, but the test in `cbstoreadapter.js` is apparently incorrect under the newer version.

**Comment by Kunal8195** [comment]
I was getting the same error when I was using the 2.2.2 version but when I updated to version 2.4.5 not getting any error. Updating to latest version worked for me.
