### ISSUE TITLE
Add appropriate restrictions for refdoc indexes with long names (>250chars)

### ISSUE THREAD

**Issue by kommunicate** [couchbaselabs/node-ottoman#160]
This is not mentioned in the documentation and the error message you get back (error code 75) is extremely counter-intuitive: `"A badly formatted packet was sent to the server. Please report this in a bug"`

In my opinion the documentation should be updated and the client should perform some checking. There's no reason to make a round trip to the server for a request that will fail anyway.

**Comment by brett19** [comment]
Sounds reasonable.  I will get something in to handle this soon.

**Comment by kommunicate** [comment]
Just adding onto this, it looks like `refdoc` indices are also immutable. If you try to `.save()` an object that was created with a `refdoc` field, you can't update that particular field and the `.save()` will fail. It gives another confusing error message that makes it sound like you're trying to update the object's ID field.

**Comment by gsi-alejandro** [comment]
Done in Ottoman v2
