### ISSUE TITLE
Query By View and Apply Sorting

### ISSUE THREAD

**Issue by lan-nguyen91** [couchbaselabs/node-ottoman#162]
Is there a way to query by View and apply Sorting on particular `key`. I can not use **N1QL** because it is extremely slow, switching to view is much faster but there is limitation of how you can sort the data.

Ex of data:
```{
      "create_at": "2017-02-18T00:08:20.252Z",
      "notification": {
        "message": "email verified",
        "data": null
      },
      "user_id": "a9a3c2ac289b2b8de82c5ca595c7e2c7",
      "type": "email",
      "viewed": false,
      "acted": false,
      "timestamp": 1487376500,
      "id": "0850eff3-820a-42d0-8068-df86e1f53dd6"
    }
```

this is how i create the index under `notification` schema

```     
... imple
 "findByUserId" : {
        "by" : "user_id",
        "type" : "view",
        "consistency" : "GLOBAL"
      },
```

how I call the function

```
  let list = yield collections.notification.findByUserId(userId, { limit : 10 });
```
So basically I want to sort by the **timestamp**, but there is no way to do it with ottoman, I dig down couchbase library but doesn't seem to make any progress. Can you please help.

The list returned fine, I guess I could do sorting on JS side, but am trying to figure out a way to sort via the DB, which I assume would be much faster.

Thanks,

**Comment by brett19** [comment]
Hey @lan-nguyen91,

Unfortunately I do not believe that views are able to sort by a key which is not the part of the view's index.  Due to this limitation, you likely will not be able to sort by a timestamp, while also filtering by a user ID (unless you want only a single user_id, in which case you could make a view index on `['user_id', 'created_at']`, and then use group_level to sort at the created_at level.

P.S. What kind of performance difference are you seeing between N1QL and Views?

Cheers, Brett

**Comment by lan-nguyen91** [comment]
i have to modify the code, because apparently the building part of the multiple indexes is not working, therefore the second index is never created. 

1. the regex doesn't work so this is my fix
(https://github.com/lan-nguyen91/node-ottoman/commit/b0f982b6279576376df7c2d055ce589d5ca48536#diff-32c7fd8401d56da3209f3c303a272558R359)

2. building of the defer index is not matching the syntax
(https://github.com/lan-nguyen91/node-ottoman/commit/b0f982b6279576376df7c2d055ce589d5ca48536#diff-32c7fd8401d56da3209f3c303a272558R463)

**Comment by gsi-alejandro** [comment]
hi @lan-nguyen91 

We are upgrading Ottoman to v2 with some major enhancement, also adding support for the new nodejs SDK 3 to take advantage of many new features.

Now you can use several options to achieve many use case:
let list = yield collections.notification.findByUserId(userId, `options`);

please check the options available [here](https://docs.couchbase.com/sdk-api/couchbase-node-client/Bucket.html#viewQuery).

Best Regards.
