### ISSUE TITLE
Creating a model with a reference should accept an ID as well as the full referenced object

### ISSUE THREAD

**Issue by kommunicate** [couchbaselabs/node-ottoman#164]
Quick note: this is a feature request, not a bug.

If I have 2 models, for example, a `Department` and an `Employee` and every `Employee` requires a `Department`, I would model it like so:

`var model = ottoman.model('Employee', {
  department: { ref: 'Department' }
});`

When creating boilerplate CRUD code for the `Employee` class, it would be great not to have to fetch the full referenced `Department` object in order to persist the new `Employee`. When ottoman creates the new `Employee` document, it's saving an ID reference rather than the full object. If I know the ID I want to refer to, in my opinion, I shouldn't have to fish out the referenced object from couchbase just to save the new object. This requires an unnecessary round trip to couchbase and, more to the point, it makes it really annoying to write this boilerplate code since every `create` call needs to be aware of the fields that it needs to fetch before persisting the new document. I solved this by walking through the object fields and preloading them, but I think this should be a pretty easy to change on the ottoman side, so here are some details.

The reason ottoman currently doesn't let you do this is this piece of code from `schema.js` starting at line 556:

`} else if (type instanceof ModelRef) {
    var expectedType = context.typeByName(type.name);

    if (type.name === 'Mixed' || expectedType === Schema.Mixed) {
      // Pass; mixed references are permitted.
    } else if (!(data instanceof expectedType)) {
      // throw error
`

My suggestion is to change this code block to look for either a string / ID type for the field, or look for an _id field on the passed in object. So this line:
`    } else if (!(data instanceof expectedType)) {`

would become something like:
`    } else if (!(data instanceof expectedType) && !(data._id)) {`

Thanks for all the great work on ottoman!

**Comment by moxious** [comment]
If you know the ID of your model, you don't have to fish it out of the database.  You can do `MyModel.ref(someIdentifier)` which will create a ref object perfect for plugging into your model, which requires a ref.

**Comment by kommunicate** [comment]
Thanks @moxious! That worked so well that I didn't actually realize it had succeeded!

After writing out the saved object in express it kept showing up as `null`, up until the next time I fetched the object from couchbase. It took me a while to realize that everything was actually ok.
