### ISSUE TITLE
Previously merged PR has a clear error, blocking creation of GSI indexes in some circumstances

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#168]
See this commit:

https://github.com/couchbaselabs/node-ottoman/commit/701769c4fdace66f0e06bc1414bd9741b6619deb

This substitution needs to be made, but notice how this is a *string of a regex* not a regex.

This URL shows how the code fails to evaluate as expected: 
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=const%20test%20%3D%20'test%24asdf'%3B%0Aconsole.log(test.replace('%2F%5B%5C%5C%24%5D%2Fg'%2C%20'__'))%3B

**Comment by moxious** [comment]
Issue fixed by https://github.com/couchbaselabs/node-ottoman/pull/163

**Comment by ckaeslin** [comment]
#163 contains also other stuff, I created another PR #169 which just fixed this problem
