### ISSUE TITLE
Ottoman versions, branches and roadmap

### ISSUE THREAD

**Issue by archit** [couchbaselabs/node-ottoman#171]
Hey @brett19, what's the status on this ODM with regards to v1.0.4, branch master (which seems to be based on v1.0.4), and the v2 rewrite? I was unable to find documentation or a roadmap on this.

I'm in the process of upgrading my ExpressJS app which uses Ottoman v0.0.2, I wanted to see what was the latest in terms of Roadmap for v2 (based on the branches reported by git).

Is it close to being finished? Do you need help? What are the features its targeting?

I would be able to help out if need be, as I would like to make a decision on upgrading my app to v1.x v/s v2.x development lines.

**Comment by brett19** [comment]
Hey @archit,

I will work on creating issues for the remaining work required on v2 as well as making the list of stuff expected to be included in v2 publicly available later today.

Cheers, Brett

**Comment by brett19** [comment]
Hey @archit,

I have posted the existing roadmap we had privately to the wiki page.  You can find it here:
https://github.com/couchbaselabs/node-ottoman/wiki/V2-Roadmap

Cheers, Brett

**Comment by waffledonkey** [comment]
Are features like configurable document expiry, replication, persistence going to be supported? are they now? I can't find any docs or mentions of logical keywords in the existing source.
