### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by nomadtechie** [couchbaselabs/node-ottoman#175]
I was wondering if support for enums is on the roadmap?

**Comment by brett19** [comment]
Hey @amalahussein,
Enums are not currently on the roadmap, but you can implement them yourself using a validator which will only accept a certain set of values.  I will keep this open as a remind to consider implementing a built-in validator that does enumerations.
Cheers, Brett

**Comment by amalahussein** [comment]
Awesome, thanks, @brett19! I'm actually using Sway + Swagger in my middleware for this exact thing. It would be a great extension to the Ottoman API though.

Thanks again.
Amal

**Comment by gsi-alejandro** [comment]
We need to set priority for this feature request.
