### ISSUE TITLE
Question: How to create self referencing recursive tree models?

### ISSUE THREAD

**Issue by amalahussein** [couchbaselabs/node-ottoman#176]
Hello, 

I'm creating a model which has a recursive structure -- is there built in support for this? I can work around it for now, but it would be nice to avoid the workaround if possible. 

Additionally, if there is no support, is this on a roadmap?

Thanks, 
Amal

**Comment by brett19** [comment]
Hey @amalahussein ,
Recursive structures are supported as long as the structure is referential and not embedded, you should be able to use the name of the model (rather than a reference to the model object itself) and have this work.
Cheers, Brett

**Comment by amalahussein** [comment]
Thanks so much Brett! I just figured that out on my own and came back to close the issue. You beat me to it :-)
