### ISSUE TITLE
the version 2.4.1 support the cb 5.0?

### ISSUE THREAD

**Issue by zhuangpeng** [couchbaselabs/node-ottoman#181]
can I use v2.4.1 with the cb 5.0?

thank you for reply!

**Comment by brett19** [comment]
You certainly can, you simply need to pass the specific couchbase version you are using to Ottoman.  We plan to address this in a release soon.

**Comment by zhuangpeng** [comment]
thank you for reply.
I use node.js v8.3.0, when I use comment to link the Id with other document, it's seem not work.
my question is: what evnvoriment (etc. node.js and syncgate) can work fine?

thanks!
