### ISSUE TITLE
Reuse of email to re-create the couchbase ottoman model

### ISSUE THREAD

**Issue by brijeshagarwal** [couchbaselabs/node-ottoman#182]
I'm using couchbase ottoman for my application.
I have created two models **users** and **groups** as mentioned below:- 

    var getGroupModel = function(ottoman){
    	if(ottoman.typeByName('groups')){
    		return ottoman.typeByName('groups');
    	}
    
    	return ottoman.model('groups', {
    	    group_name: 'string',
    	    created_by: {ref: 'users'},
    	}, {
    	    index: {
    	        findByCreator: {
    	            by: 'created_by.email',
    	            type: 'refdoc'
    			},
    			findByCreatorId: {
    	            by: 'created_by._id',
    	            type: 'refdoc'
    			},
    			findById: {
    				by: '_id',
    				type: 'refdoc'
    			}
    	    }
    	});
    }
    
    var getUserModel = function(ottoman){
    	if(ottoman.typeByName('users')){
    		return ottoman.typeByName('users');
    	}
    
    	return ottoman.model('users', {
    	    first_name: 'string',
    	    last_name: 'string',
    	    email: 'string',	   
    	    groupId: {ref: 'groups'},

    	}, {
    	    index: {
    	        findByEmail: {
    	            by: 'email',
    	            type: 'refdoc'
    			},
    			findById: {
    				by: '_id',
    				type: 'refdoc'
    			}
    	    }
    	});
    }

I use ottoman's **.create()** method to create new Users and group. So it craetes user successfully for the first time. Then I remove the both user and group using otomans **.remove()** method and then after try to create user and group back again. It gives me a **CAS ERROR** mentioned below:-

    { 
      success: false,
      error:
       { 
           message: 'The key already exists in the server. If you have 
           supplied a CAS then the key exists with a CAS value different than 
           specified', code: 12
       }
    }.

I'm unable to figure out how I should delete the data, So it is completely removed from the ottoman model and I'm able to reuse the same email again.

**Comment by brett19** [comment]
Hey @brijeshagarwal ,
Can you look at the Web UI for your cluster after creating/removing and identify the document which is failing to be removed appropriately?  I imagine there is some circular dependancy that Ottoman is failing to resolve during removal.  Knowing what document is being left behind will help identify the exact issue.
Cheers, Brett

**Comment by brijeshagarwal** [comment]
hey @brett19 ,
I have deleted both the documents from ottoman. I have the _id of both the document. After creating the document it did reflected in workbench also and after removing the documents, documents are also not found via couchbase workbench. That means the remove has deleted the document and the when I try to reuse the same data to create the documents. I'm getting CAS already exists error.

So where should I look, if document is completely removed or not and if now, what part of documenst is left. And how to remove it?

**Comment by brett19** [comment]
Hey @brijeshagarwal ,
So your saying that the bucket has no documents in it, but the creation of the model fails due to a CAS error?

**Comment by brijeshagarwal** [comment]
I think so, If not that is, if document is not completely removed how do I know what part of document is not deleted and how do i retrieve it and delete it further. Couchbase workbench does not return any document after I remove it via ottoman's .remove method succesfully. So where is the error?

And that too error is just in group creation, user is re-created but group is not created back with same email.
