### ISSUE TITLE
Find in Array

### ISSUE THREAD

**Issue by LordNoteworthy** [couchbaselabs/node-ottoman#183]
Hello,

First, thanks a lot of this nice ODM. 

I have a simple question which is : I have a model like this:

```
ottoman.model('User', {
  name: 'string',
  roles: ['string']
}, {
  index: {
    findByRoles: {
      by: 'roles',
      type: 'n1ql'
    }
  }
});
```

I would like to search over `roles` by providing a string. Is it possible ? because I am not able to find an example in the documentation.

Info: Couchbase 4.5,  ottoman: 1.0.4

Thank you.

**Comment by 777sha** [comment]
I'd like to know if there is a way as well

**Comment by brett19** [comment]
Hey @LordNoteworthy and @777sha,
I'm not confident I understand what you are asking for here.  Are you looking to search for documents using N1QL that contain a specific role?  You should be able to specify `roles[*]` as your `by` value on the index definition to search in that way.
Cheers, Brett

**Comment by DanlanNZ** [comment]
@LordNoteworthy @777sha you could also use something like this to avoid defining an index for each query
```js
User.find({role: { $contains: 'value' } })
```
@brett19 I assume defining an index on a model has better performance but I'm not sure if Ottoman builds GSI indexes. We do this manually for slow queries when necessary

**Comment by brett19** [comment]
Hey @DanlanNZ ,
It is possible to generate GSI indices by specifying the `type` value as @LordNoteworthy did above.
Cheers, Brett
