### ISSUE TITLE
.find ignores arguments of Date type.

### ISSUE THREAD

**Issue by ibugaienko** [couchbaselabs/node-ottoman#184]
Hello @brett19 ,

I ran into this issue at work, arguments of `Date` type get thrown away from resulting query, e.g.:
```
MyModel = ottoman.model(modelId, {
        when: 'Date'
      });
MyModel.find({when: new Date()}, {}, function (err, res) { ... })
```
`res` will end up having everything matching query which looks like
    ```SELECT  * FROM `bucketName` WHERE _type='MyModel'```

The fix is simple and I have already put it here e108fb994da39604cda5da747c51678cec3f1da8, so if you do not mind I would create a pull request.

Please let me know, thanks!

**Comment by brett19** [comment]
lgtm.  Post a pull request and I'll be happy to merge.  Definitely a bug that this wasn't included originally!
