### ISSUE TITLE
No bucket close functionality in node couchbase SDK

### ISSUE THREAD

**Issue by kommunicate** [couchbaselabs/node-ottoman#186]
These are issues in the couchbase  library but since it affects ottoman too I'm listing them here (also, sorry, but I can't seem to access the forums or your other bug tracker to file it in the right place).

**Missing Close:**
There is no `.close()` in either the bucket or cluster couchbase functions. This is an issue for a few reasons (most notably, pending operations will get dropped). In my case, upgrading to `mocha 4` caused tests to hang forever with no available workarounds or suggested solutions having any effect. After tracing the issue down, I believe the root cause is that the connection to couchbase is left open with no way to close it. Here's a description of the issue from the [mocha side](https://github.com/mochajs/mocha/issues/3044). Notably, the suggestion of invoking `mocha` with `--exit` does not work.

Turning to the couchbase side, here's the [JS SDK](https://developer.couchbase.com/documentation/server/current/sdk/nodejs/start-using-sdk.html). Noticeably there's no `.close()` after the demo code. Other language SDKs have this functionality (example: [Java](https://developer.couchbase.com/documentation/server/current/sdk/java/start-using-sdk.html)) and call attention to it's importance. The missing functionality seems to be limited to the JS SDK. I can see that the `C++` driver is generating the `.close()` functionality, it just seems to be that the javascript package doesn't add the necessary hook to invoke it. 

**Disconnect:**
During my investigation into this issue, I tried using `bucket.disconnect()` but discovered that after the the bucket doesn't get reopened again properly, instead throwing the following error:

~~~javascript
    Error: cannot perform operations on a shutdown bucket
        at Bucket._maybeInvoke (node_modules/couchbase/lib/bucket.js:1107:11)
        at BucketManager._capiRequest (node_modules/couchbase/lib/bucketmgr.js:65:5)
        at BucketManager.upsertDesignDocument (node_modules/couchbase/lib/bucketmgr.js:152:8)
        at CbStoreAdapter._ensureMrIndices (node_modules/ottoman/lib/cbstoreadapter.js:311:15)
        at CbStoreAdapter.ensureIndices (node_modules/ottoman/lib/cbstoreadapter.js:488:8)
        at _ensureAllStores (node_modules/ottoman/lib/ottoman.js:947:17)
        at handler (node_modules/ottoman/lib/ottoman.js:962:9)
        at handler (node_modules/ottoman/lib/ottoman.js:894:7)
        at node_modules/ottoman/lib/cbstoreadapter.js:192:7
        at process._tickCallback (internal/process/next_tick.js:150:11)
~~~

I *think* this is because `this.connected` is getting set to `false` before the call to `shutdown` and that there's some race condition taking effect, but this is a bit tricky to verify on my side. Here's the `disconnect` [code](https://github.com/couchbase/couchnode/blob/master/lib/bucket.js#L286):

~~~javascript
Bucket.prototype.disconnect = function() {
  if (this.connected !== false) {
    this.connected = false;
    this._cb.shutdown();
  }
};
~~~

**Comment by brett19** [comment]
Hey @kommunicate,

You can close the underlying bucket for ottoman by invoking the following code which will close the bucket associated with the ottoman instance (if you have not stored it externally):
```javascript
ottoman.bucket.disconnect();
```

In terms of the disconnect behaviour you are seeing, there is an open issue tracking the resolution of some confusing behaviour which you can find here:
https://issues.couchbase.com/browse/JSCBC-421

Cheers, Brett
