### ISSUE TITLE
Connect other in other port.

### ISSUE THREAD

**Issue by kivervinicius** [couchbaselabs/node-ottoman#192]
Hi, I need connect ottoman in other port different 8091, if i pass on http://127.0.0.1:58091 the service principal works, but service query dont, i obtain one error called message:"password required", but password is filled, and if i connect on normal port works.

I need this because i have two containers docker to emulate different ambients (production vs beta)

```
Error: User does not have credentials to run SELECT queries on the notificacao bucket. Add role query_select on notificacao to allow the query to run.
```

**Comment by brett19** [comment]
Hey @kivervinicius,
Would you be able to provide a code-snippet showing how you are connecting to Couchbase?  We test using custom port numbers as part of our test runner, so I am surprised that it is not working!
Cheers, Brett

**Comment by kivervinicius** [comment]
Hi, @brett19 `var cluster = new couchbase.Cluster("http://127.0.0.1:58091?detailed_errcodes=1");`

**Comment by brett19** [comment]
Hey @kivervinicius,
Can you try to use a `couchbase://` scheme along with the memcached port for your cluster (that would be your version of 11210)?  Using the `http://` scheme in a connection string is a legacy backwards-compatibility thing.
Cheers, Brett

**Comment by kivervinicius** [comment]
Then i would connect `var cluster = new couchbase.Cluster("couchbase://127.0.0.1:58091?detailed_errcodes=1");`
