### ISSUE TITLE
 How to use the field name is `id`?

### ISSUE THREAD

**Issue by anhnam00** [couchbaselabs/node-ottoman#196]
My data base already existed before I used ottoman. And all my models use the `id` field. Now i'm having a error message:  'No user-defined fields may have the name `id`'.

**Comment by brett19** [comment]
There is not currently a path enabling the use of custom id field naming.  The next generation version of Ottoman does support custom naming schemes, but it will not be available until later this year.  One option currently is to fork ottoman and make the id field naming changes manually.
