### ISSUE TITLE
Add support for projections

### ISSUE THREAD

**Issue by sm2017** [couchbaselabs/node-ottoman#198]
How can I use projection in node-ottoman to save network bandwidth ?

In the following model

```js
var Furniture = ottoman.model('Furniture', {
  name: 'string',
  title: 'string',
  AndManyManyOtherFields
}, {
  index: {
    findByName: {
      by: 'name'
    }
  }
});
```

If I execute

```js
Furniture.findByName('table', function(err, tables) {
  if (err) return console.error(err);
  console.log(tables);
})
```

The `tables` contains all fields that just kill network bandwidth , I only need some fields , How can I explicitly project some fields?

**Comment by brett19** [comment]
Hey @sm2017 ,
Ottoman itself does not support projections due to the nature of its object mapping.  It may be worthwhile to support some form of arbitrary querying which does not use object mapping in the future, but I'm not quite sure how that would work at this point.
Cheers, Brett

**Comment by sm2017** [comment]
I know that **[Couchbase beats MongoDB](https://blog.couchbase.com/couchbase-beats-mongodb-with-greater-flexibility-and-stronger-availability-for-geo-distributed-applications/)** , but really **mongoose** beats  ottoman

https://mongoosejs.com/docs/api.html#model_Model.findOne has projection

**Comment by gsi-alejandro** [comment]
hi @sm2017 

Ottoman v2 already implement something similar to mongoose projection, using the select feature while querying:

please check the documentation -> https://v2.ottomanjs.com/guides/model.html#querying

We are improving Ottoman, if you have any other requests please share them.
Thank you for your help.
