### ISSUE TITLE
How to change key format  User|300 -> user_300?

### ISSUE THREAD

**Issue by anhnam00** [couchbaselabs/node-ottoman#199]

**Comment by kivervinicius** [comment]
why?

**Comment by anhnam00** [comment]
Because my db is created with that format  before i used this library. Thanks for your reply.

**Comment by kivervinicius** [comment]
Well, in file https://github.com/couchbaselabs/node-ottoman/blob/c31cee25326dadaa53172021c075c55f78b0cd4f/lib/modelinstance.js#L159 in this line it does not have any kind of customization, however you could easily change it to a customization and do a pull request, what do you think?

**Comment by anhnam00** [comment]
yes, i know that line. but i think it should be a option that can be customized

**Comment by kivervinicius** [comment]
yeap, feel free to fix this.

**Comment by brett19** [comment]
Hey!  The in development v2 version of Ottoman does support this feature, and we would be happy to accept Pull Requests against v1 to implement it as well.
Cheers, Brett
