### ISSUE TITLE
Node gyp build error on node.js 10

### ISSUE THREAD

**Issue by hug0b** [couchbaselabs/node-ottoman#203]
running `npm install ottoman` on Node.js 10.15.0 throws a gyp build error.

using Pop OS (Ubuntu 18.10). 
I tried on windows 10 earlier and ran into the same issue which was gone when switching to Node.js 8.

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.19.14-041914-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/hugo/WD Blue 1T/public_html/My-API/server/testottoman/node_modules/couchbase
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by brett19** [comment]
I believe this is related to missing build tools.

**Comment by 777sha** [comment]
This is weird I have the following packages installed in their latest versions but the error is still happening :

> build-essential
> gcc
> g++
> make

**Comment by brett19** [comment]
Closing as this is actually related to the underlying Node.js SDK as opposed to Ottoman itself.  Feel free to file an issue against the core SDK if you are continuing to experience build issues.
