### ISSUE TITLE
What is the latest couchbase version supported by ottoman 1.05 ?

### ISSUE THREAD

**Issue by NoSoup4you2** [couchbaselabs/node-ottoman#204]
I am trying to get ottoman to work with couchbase node sdk on a windows based system with little to no luck. Originally i had couchbase sdk 2.6.0 installed but got the following error.

Error: The couchbase module version used by the application does not match Ottomans.  Please explicitly pass the application couchbase module using `StoreAdapter.Couchbase`.

after digging i could not find any specific docs how to pass the module. I down graded to couchbase 2.4.2 but that did not solve the problem either. The only way i was for now able to make this work is by using 
const couchbase = require('ottoman/node_modules/couchbase')

So i hope someone can shed some light on this issue how to correctly install couchbase and ottomon to avoid any of these errors based on current version. All docs i found are years old and dont solve any of these issues.

**Comment by hug0b** [comment]
@NoSoup4you2 I am using couchbase 2.6.0 and ottoman 1.0.5 without this issue

**Comment by brett19** [comment]
The latest version of Couchbase Node.js SDK is always guaranteed to be supported by latest version of Ottoman.  In some cases, with older versions of Node.js which have independant dependancy resolution, you may need to do something like the following:
```
var couchbase = require('couchbase');
var ottoman = require('ottoman');
ottoman.store = new ottoman.CbStoreAdapter(couchbase);
```
