### ISSUE TITLE
Please update this ODM

### ISSUE THREAD

**Issue by agmt5989** [couchbaselabs/node-ottoman#206]
I realize that the de facto method for connecting to Couchbase from a node.js application is the native couchbase driver. But some of us with backgrounds using mongoose for Node-MongoDB development are interested in Ottoman. Now I can't help noticing that its build is failing, and it's not got any serious commits in the past couple of years. Most users will be understandably skeptical, and this must account for the disparity in npm downloads between this and couchbase.
Please update this repo. Hundreds of developers are counting on this.

**Comment by ingenthr** [comment]
hey @agmt5989 - we've been working mostly on some changes in the base SDK to then make some more changes in Ottoman.

**Comment by brett19** [comment]
Just to add to ingenthr's comments.  We have been hard at work on the latest 3.0 version of our Couchbase Node.js SDK.  We are hoping to have a version 3.0 compatible and updated Ottoman.js with support for Promises, Async/Await and Proxies by the end of the year!
