### ISSUE TITLE
give a choice to configure to be able use the standard ES6 Promise?

### ISSUE THREAD

**Issue by c0b** [couchbaselabs/node-ottoman#207]
like this talk I initiated `how to configure to use the standard ES6 Promise?` tgriesser/knex#1588 back in 2016, it turns out the native Promise is getting better and better, there's no more reason to continue depend on a 3rd party Promise implementation,

at least, give users a choice to user different one, like https://www.npmjs.com/package/promise-queue,  user can explicitly configure it by `Queue.configure(require('vow').Promise);`

So can this package implement a similar strategy?

**Comment by brett19** [comment]
Hey @c0b ,
There is an updated version of Ottoman under development which takes advantage of newer ECMAScript 6 features such as Promises, Async/Await and Proxies.  We are hoping to have this available later this year.
Cheers, Brett
