### ISSUE TITLE
Using a n1ql index I get "Error: Could not find gsi index configuration"

### ISSUE THREAD

**Issue by dalborgo** [couchbaselabs/node-ottoman#212]
Couchbase version: Enterprise Edition 5.1.0 build 5552
Ottoman version: 1.0.5
Couchbase dependency: 2.6.4

```
 index: {
      findByOrgId: {
        by: 'cynation.orgId',
        type:'n1ql'
      }
    }
```
The index is created and it is built.
When I call `findByOrgId ` I get "Error: Could not find gsi index configuration"

If I define the index in this other way (a view index) everything works properly: 
```
 index: {
      findByOrgId: {
        by: 'cynation.orgId'
      }
    }
```

**Comment by brett19** [comment]
Hey @dalborgo,
Can you try to have your index work on a direct field `orgId` rather than compound `cynation.orgId` as a test?  See if that changes the outcome.
Cheers, Brett

**Comment by dalborgo** [comment]
I have already testing with a field at deep level zero getting the same error.

```
index: {
      findByOrgId: {
        by: 'orgId',
        type:'n1ql'
      }
 }
```

**Comment by AV25242** [comment]
This should be fixed in Ottoman V2
