### ISSUE TITLE
Wanting more information on future of ottoman

### ISSUE THREAD

**Issue by ethanbensonagc** [couchbaselabs/node-ottoman#213]
Hello - my team & I are interested in relying very heavily on node-ottoman for production software, so we'd like to know more about the future of ottoman. How actively is it being updated, what's the release schedule like, how often are features added, etc.? We're mulling over whether we should rely on this version of ottoman or fork it ourselves to start updating and modifying it ourselves. Thanks!!

**Comment by brett19** [comment]
Hey @ethanbensonagc,

Ottoman.js is still a supported project, and while we are currently working hard on the 3.0 release of our Node.js SDK to coincide with the upcoming major server release we still intend to continue development on Ottoman.js.  We are expecting to have a new major release of Ottoman by the end of the year.  Additionally, we are always super-excited to see contributions from the community, and are always willing to work with everyone to get awesome changes merged into the project!

Cheers, Brett
