### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by alinauroz** [couchbaselabs/node-ottoman#223]
Im trying to run ottoman example that was provided on github page. This gives authentication error.

[CouchbaseError: Authentication failed. You may have provided an invalid username/password combination] {
  message: 'Authentication failed. You may have provided an invalid username/password combination',
  code: 2
}

**Comment by httpJunkie** [comment]
Could you give us more info on the version of Node, Couchbase Server and Couchbase Node SDK you are using?

**Comment by AV25242** [comment]
Closing this issue for no response
