### ISSUE TITLE
Support for Couchbase@3.0.2

### ISSUE THREAD

**Issue by Dhruv-Aga** [couchbaselabs/node-ottoman#228]
I was starting a new project using ExpressJs + Couchbase, I tried to use ottoman but every time encountered the error, ultimately i found that ottoman does not support the Couchbase@3.x.x.  

I know it takes time to update a library, but my query is 

>Are the ottoman going to support the Couchbase@3.x.x in future or not?  

Till the time, I will like to suggest that we should change the documentation to mention that it only supports counchbase@2.x.x.

**Comment by Xiad32** [comment]
+1

**Comment by hubgit** [comment]
The `couchbase` dependency in the master branch is now v3.0.4

https://github.com/couchbaselabs/node-ottoman/blob/7a2fc9747f4b9532d348072f6974e3c0416c33d7/package.json#L74

It looks like installing `ottoman@alpha` should install the latest alpha version, currently 2.0.0-alpha.8

**Comment by AV25242** [comment]
@Dhruv-Aga , @Xiad32 , @hubgit   Ottoman V2 is in the process of being built (Currently in alpha) . It sits on top of Couchbase Node.js SDK 3.0. You can see the documentation [here](https://v2.ottomanjs.com/).

**Comment by AV25242** [comment]
Closing this issue for now
