### ISSUE TITLE
Allow range querying of indexes.

### ISSUE THREAD

**Issue by brett19** [couchbaselabs/node-ottoman#29]
Doing queries based on a range of values rather than a solid value should be supported.

**Comment by CodestarGames** [comment]
Yeah I need to query models by a date range and I cannot figure out how to do it with node-ottoman

**Comment by gsi-chao** [comment]
In the ottoman v2 you can make complex queries using the Model .find () method or using an N1QL query with the query builder. See full examples in this link: https://v2.ottomanjs.com/guides/query-builder.html#advanced-example-of-using-the-where-clause
Eg:
```
User.find({birthday: {$btw: ['2020-01-02', '2020-12-30']}})
```

_BETWEEN
"Search criteria for a query where the value is between two values, including the end values specified in the range. Values can be numbers, text, or dates."_
