### ISSUE TITLE
Ottoman V2 Typescript Example Project and Documentation

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#302]
Once #210  is completed, need to provide a sample project built using Typescript for Ottoman and Documentation must be updated to include code samples on a page exclusive for Typescript Support 

Something like  " Using Ottoman with Typescript "  (This label can be changed later and is only a thought at this point)

**Comment by gsi-chao** [comment]
Created repository with updated Ottoman Example code in Typescript
https://github.com/couchbaselabs/try-ottoman-ts

**Comment by httpJunkie** [comment]
So far this looks good and works as intended
Readme.md seems to have necessary instructions
Testing with Postman using the Swagger API to guide me.
