### ISSUE TITLE
Extend Model - Provide removeMany Support

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#304]
Declare and/or execute this query as a remove() operation, matches filter condition and removes all documents and its associated ref-doc index from  the collection.

Model.remove(filter)

**Returns**
ok: 1 if no errors occurred
Count : the number of documents removed

**Comment by AV25242** [comment]
@gsi-alejandro  considering we have consistent naming conventions we should probably name this method r**emoveMany instead of deleteMany**

**Comment by httpJunkie** [comment]
This is the ticket blocking

https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/51

**Comment by AV25242** [comment]
Closing this ticket
