### ISSUE TITLE
Rename remove method to removeById

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#305]
Removes the Document from the collection where Id matches the value provided.

`await Model.removeById(  '12345' );`

returns Ok for success

**Comment by bwgjoseph** [comment]
Hi @AV25242,

Why object? Does it auto infer the `key` if pass using object?

Passing  `await Model.deleteById('12345');` instead or even `await Model.deleteById(12345);` should work as well?
