### ISSUE TITLE
connection.dropScope()

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#307]
connection.dropScope()
**Parameters**
collection «string» The Scope to delete
[callback] «Function»
Returns:
«Promise»
Helper for dropScope(). Will delete the given Scope, including all Collections,  documents and indexes inside the scope.

**Comment by httpJunkie** [comment]
Blocked:
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/4

**Comment by AV25242** [comment]
Even though the issue on the customer side is still open, the latest comments indicates that these issues can be closed. We may open a new issue as needed
