### ISSUE TITLE
connection.dropBucket

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#312]
connection.dropBucket()
Parameters
bucket «string» The bucket to delete
[callback] «Function»
Returns:
«Promise»
Drops the bucket, and all scopes, collections, indexes and documents within the bucket.

**Comment by httpJunkie** [comment]
Blocked:
bwgjoseph/mongoose-vs-ottoman#4

**Comment by AV25242** [comment]
Even though the issue on the customer side is still open, the latest comments indicates that these issues can be closed. We may open a new issue as needed
