### ISSUE TITLE
default values of fields in lists are ignored.

### ISSUE THREAD

**Issue by brett19** [couchbaselabs/node-ottoman#32]
When specifying a Schema list, that contains a Group with fields with default values, the default values are never set as the object that is added to the list comes from the user rather than being created by ottoman.  Solution may be to have a .push overload on ottoman lists that applies defaults that are missing.

**Comment by brett19** [comment]
Additional restrictions are going to be placed on the definition and use of list objects within Ottoman Models.  This will allow us to enforce the various validations for the list, and as part of this, default values will be applied to schemas which are used inside of lists.  The changes primarily include removing the ability to define a list with an implicit schema being used for it contents (since this would not be user-constructible without a reference to the object type), as well as lists being a special form of list managed by ottoman, where pushing to the list will trigger various validations.

**Comment by insanesvk** [comment]
any ETA on this?
