### ISSUE TITLE
Fix : import ottoman from 'ottoman'

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#320]
My project has esModuleInterop set to true but import ottoman from 'ottoman' doesn't work. I tried to print out ottoman and it is undefined

**Comment by gsi-alejandro** [comment]
To import Ottoman resources, the following 2 syntaxes can be used:

```
import * as ottoman from 'ottoman';
ottoman.connect(....)
```

or

```
import { connect } from 'ottoman';
connect(....)
```

Sorry, but `import ottoman from 'ottoman` will not work even when esModuleInterop is set to true in tsconfig.json
