### ISSUE TITLE
This library can not work in pure javascript or in framework like angular what Can I use then?

### ISSUE THREAD

**Issue by richard457** [couchbaselabs/node-ottoman#332]
This is not an issue but a general understanding of what can be used in an environment like angular, I tried http://pouchdb.com/ but they officially say that sync gateway is not 100 % supported, could you please guide me in the right direction.

**Comment by AV25242** [comment]
Hello @richard457  Ottoman is an ODM for Couchbase and not CouchDB.

**Comment by richard457** [comment]
I understand, My question is that what can be used in the angular project? not node.js environment is there any library for browser? @AV25242

**Comment by richard457** [comment]
Please suggest to me what to use to achieve maximum sync between mobile devices and browsers.
