### ISSUE TITLE
Provide Generics Support in Typescript

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#333]
Provide support for Generics in the Typescript version of Ottoman such that as a Developer I should be able to define an Interface such that the intellisense  knows how to infer the fields from my interface.

**Comment by anonrig** [comment]
hey @gsi-alejandro what's the status of this task? do you need any help?

**Comment by adhorodyski** [comment]
Hi @gsi-alejandro, are there any problems related with this task?
As a team we're highly awaiting generics support for fully type-safe experience, right now we're really missing them at our models. Maybe there's a way we can help?

**Comment by AV25242** [comment]
Hello @adhorodyski  good to know that you are using Ottoman, I dont think there is any issue with this task, this was picked up towards the end on purpose so that we can resolve other issues and get to this one as this one would be a major task.
the last heard from @gsi-alejandro  was that he is close

@gsi-ariam  any updates ?

Also @adhorodyski  what is your use case for Ottoman, if you can share it would help !
