### ISSUE TITLE
support for Bulk Create (CreateMany)

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#336]
Extend current Create Method to allow to pass in multiple documents 

Current Implementation 
`
const user = await User.create({name: "John Doe"});`

Extend this to

`const result = await User.create( [ {name: "John Doe"}, {name: "Tony Stark"}]);`

result should contain
Count of number of documents inserted.
Error if any

**Comment by httpJunkie** [comment]
Blocked by
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/51

**Comment by AV25242** [comment]
Closing as the main issue is closed
