### ISSUE TITLE
There isn't a connection available to create Model XXX

### ISSUE THREAD

**Issue by ceddybi** [couchbaselabs/node-ottoman#344]
I think this should be improved,

Here's a case

`model.ts`
```ts
const schema = {...}

export const myModel = model('MyModel', schema);
```

Now from my main app
`app.ts`

```ts
import model from ''./model"

main function(){
    // define some functions/routes that use the model
    
    // then run the `ottoman.start` function below
}
```

Error is thrown because I've defined the model without calling the start function first, kinda weird, I don't know how you'd use this for maintainable code

**Comment by ceddybi** [comment]
Just ran it as a function

`export const UserModel = () => model('User', userSchema);`

**Comment by anonrig** [comment]
model actually returns a ConnectionManager where you can call `model.start()` directly without referencing to the `import { start} from 'ottoman'`

**Comment by ceddybi** [comment]
@anonrig that would mean I have to call `model.start()` from all models, - isn't that against calling `start` multiple times?

I basically just wanted a re-usable model where I can import and call it from multiple places `before calling the start method` 

Before it was like this

```ts
export const myModel = model('MyModel', schema);

import myModel ...

myModel.find()

```

this throws an error because am calling `model(name, schema)`, without calling the `start` method


Now I just export it as a function,

```ts
export const myModel = () => model('MyModel', schema);

myModel().find()
```
This works even if I haven't called the `start` method, because am exporting it as a function, so I haven't called the `model(name, schema)` yet
