### ISSUE TITLE
Error: parent cluster object has been closed

### ISSUE THREAD

**Issue by zonorion** [couchbaselabs/node-ottoman#349]
Hi, im new with ottoman, i try to call model findOne()
Here is my model declare:
`import { model, Ottoman, Schema } from 'ottoman'
import { KEY_GENERATOR, PRICING_MODELS } from '../../consts'

const ottoman = new Ottoman()
ottoman.connect('couchbase://****)

export const PriceSchema = new Schema({
    propertyId: { type: String, required: true },
    roomId: { type: String, required: true },
    agreementId: { type: String, required: true },
    rateId: { type: String, required: true },
    rateType: { type: String, required: true },
    allotment: Number,
    price: { type: Number, required: true },
    isActive: { type: Boolean, required: true },
    status: String,
    date: { type: String, required: true },
})

export const PriceModel = model(PRICING_MODELS.PRICE, PriceSchema, {
    collectionName: 'prices',
    keyGenerator: KEY_GENERATOR,
})`

and 
`const test = await PriceModel.findOne()
console.log(test)
`

But i got error: Error: parent cluster object has been closed.  Please tell me why? Thanks

**Comment by AV25242** [comment]
Hello @zonorion thanks for reaching out, I see you are using a collectionName. Which version of CB server are you using ?

**Comment by zonorion** [comment]
> Hello @zonorion thanks for reaching out, I see you are using a collectionName. Which version of CB server are you using ?

Hi, thanks for reply. I'm using Community Edition 6.6.0 build 7909

**Comment by AV25242** [comment]
6.6 by default doesnt support collections

try to replace 

```
export const PriceModel = model(PRICING_MODELS.PRICE, PriceSchema, {
collectionName: 'prices',
keyGenerator: KEY_GENERATOR,
})`
```

with

export const PriceModel = model('prices', PriceSchema)`

**Comment by zonorion** [comment]
I try to using model(PRICING_MODELS.PRICE, PriceSchema, { keyGenerator: KEY_GENERATOR })
But i got new error:
`context: QueryErrorContext {
    first_error_code: 3000,
    first_error_message: 'Ambiguous reference to field hotel_pricing.',
    statement: 'SELECT `prices`.* FROM `hotel_pricing`.`_default`.`prices` WHERE _type="prices" LIMIT 1',
    client_context_id: 'dc7f3f5fd72940d1',
    parameters: '',
    http_response_code: 400,
    http_response_body: ''
  }
}`

**Comment by AV25242** [comment]
Thats good, which means you are passed connection issue, its bit vague to me. What is hotel_pricing. Is your code anywhere in github. ?

**Comment by zonorion** [comment]
PRICING_MODELS.PRICE = 'prices', 'hotel_pricing' is my bucket name, my code is private project on gitlab :(

**Comment by AV25242** [comment]
Thanks no problem @gsi-alejandro  looks like this may be a bug. I would expect the query generated for findOne to be 
'select * from hotel_pricing where _type="prices" limit 1"
can you please see if there is something that is being missed ?

**Comment by AV25242** [comment]
failed to ask are you using alpha.12 ? the latest version ?

**Comment by zonorion** [comment]
> failed to ask are you using alpha.12 ? the latest version ?
Yes, im using latest version 
"ottoman": "^2.0.0-alpha.12"

**Comment by AV25242** [comment]
Thank you, will see that you get some help here. Thanks for your patience.

**Comment by AV25242** [comment]
@zonorion  we  strongly feel that you have the collectionName set somewhere. Since we cannot see your code can you please review your code and see that you are NOT setting collectionName anywhere ?

**Comment by zonorion** [comment]
@AV25242 
Hi, i push my code to https://github.com/zonorion/couchbase
Now i got: 
`node_modules/ottoman/lib/types/ottoman/ottoman.d.ts:63:30 - error TS2304: Cannot find name 'CollectionManager'.

63     get collectionManager(): CollectionManager;
                                ~~~~~~~~~~~~~~~~~
node_modules/ottoman/lib/types/ottoman/ottoman.d.ts:67:26 - error TS2304: Cannot find name 'BucketManager'.

67     get bucketManager(): BucketManager;`

**Comment by gsi-alejandro** [comment]
Hi @zonorion 

I already checked your repository, please follow the next two steps:
1. Change the line 20 in the file couchbase.service.ts to `const ottoman = new Ottoman({ collectionName: '_default' });` (This is needed to work with couchbase server 6.x without scopes/collections)
2. You can fix the types error by setting this line in the tsconfig.json `"skipLibCheck": true` (This bug will be fixed in the next alpha.13)

With the above steps, you must go ok.

Note:
You can remove couchbase dependency (`npm uninstall couchbase`), maybe you added this while trying to fix the types error, but it's no needed, Ottoman will provide the last couchbase version that works for the current Ottoman package.

Thank you.

**Comment by zonorion** [comment]
@gsi-alejandro thank you so much

**Comment by AV25242** [comment]
@zonorion  hope you got all the help needed, closing this issue for now. Please open another issue if need to be

**Comment by AV25242** [comment]
@zonorion  did you get all the help you needed. Also can you tell us what is your usecase and what version of CB server are you using. It will help us help others .

Appreciate it

**Comment by zonorion** [comment]
Im using Community Edition 6.6.0 build 7909 and ottoman can not working with collection. 
Should be set: 
`const ottoman = new Ottoman({ collectionName: '_default' })`

**Comment by AV25242** [comment]
Thanks @zonorion  what is the usecase you are building or application you are building.
yeah collectionName: '_default' should work

**Comment by zonorion** [comment]
Im building hotel inventory application to store price, allotment...etc

**Comment by ceddybi** [comment]
Very confusing, @gsi-alejandro @AV25242 

I set the collectionName from `new Ottoman({ collectionName: '_default'})`, then I set the model's collectionname too, I still get the errors `Ambiguous reference to field`.

 However when I only set from `new Ottoman({ collectionName: '_default'})` it works, 
 
 - does this mean that all my models will be stored in one collection, is that a good thing or a bad thing? someone, please provide some brief explanation.
 - If collections are not supported in 6.x.x why should we be setting them?


Ottoman Version: ^2.0.0-alpha.14
CB: 6.x.x

**Comment by ceddybi** [comment]
+ removing the default collection name from `new Ottoman()`, makes the queries not work, kind of weird contrary from your documentation 

https://v2.ottomanjs.com/guides/model.html#model-options

_Therefore this is the way to get the Collection name for a Model: Collection Name = Model collectionName Options > Ottoman collectionName Options > Model name_

**Comment by ceddybi** [comment]
I just want to thank you all for this thread, in the last 24 hours I decided to create my own new ORM package, highly inspired by `node-ottoman`  https://github.com/stoqey/sofa

Things make more sense now 🤘🏿🙏🍾

Please don't hesitate to throw some feedback on it

Thank you very much again
