### ISSUE TITLE
Create support for Immutable

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#373]
Need support for Immutable refer to this issue https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/45

**Comment by httpJunkie** [comment]
This is linked to Joseph's ticket here:
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/45

As well as our own ticket here:
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/45
