### ISSUE TITLE
Support for Lean

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#374]
Need support for Lean - Refer to the details here https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/43

Mongoose Ref: https://mongoosejs.com/docs/tutorials/lean.html#using-lean

**Comment by httpJunkie** [comment]
This is linked to Joseph's ticket here:
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/43

No internal ticket...

**Comment by AV25242** [comment]
This issue is fixed. Closing this for now
