### ISSUE TITLE
Prepend Document Key with Model Name instead of Scope$CollectionName By Default

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#375]
Fix KeyGenerator default behavior to prepend Model Name

**Comment by gsi-alejandro** [comment]
keyGenerator default function will be update to:
`keyGenerator = ({metadata}) => `${metadata.modelName}``

Notice: **id** is no longer available for the user as an argument.

keyGenerator specifications:

1. keyGenerator only will provide a prefix for the key.
2. Ottoman will add a **delimiter (::)** and the **id** value as a suffix.

Example:
User will be able to set:
for a model with this definition model('User', ...)
and this keyGenerator definition
`keyGenerator = ({metadata}) => `${metadata.modelName}``

the result will be:
`User`

Then Ottoman will set the suffix:
`::745767`

Overall result for the key will be something like:
`User::745767`

**Comment by xavierchow** [comment]
@gsi-alejandro 
I think the doc here: https://ottomanjs.com/guides/ottoman.html#ottoman-constructor-options needs to be updated accordingly.(I'm glad to send a PR if needed)

<image src="https://user-images.githubusercontent.com/2748884/146338639-8fe80fe3-efe7-4619-bf7c-c1b3029b9430.png" width=680 />

I was quite confused until I found this Github issue.
