### ISSUE TITLE
LCB_ERR_SDK_FEATURE_UNAVAILABLE

### ISSUE THREAD

**Issue by sm2017** [couchbaselabs/node-ottoman#379]
> (node:5944) UnhandledPromiseRejectionWarning: Error: LCB_ERR_SDK_FEATURE_UNAVAILABLE (1029): The requested feature is not supported by the client, either because of settings in the configured instance, or because of options disabled at the time the library was compiled

Why I am getting the error?

I am using ottoman@2.0.0-alpha.14 and nodejs v14.15.4

```js
import { connect, model } from "ottoman";
connect("couchbase://localhost/travel-sample@admin:password");

const User = model('User', { name: String });

const user = new User({name:'Jane Doe'});
user.save().then(() => console.log('Nice Job!'));
```

**Comment by sm2017** [comment]
I am using Windows 10

**Comment by AV25242** [comment]
I am assuming you are using Couchbase server version that doesnt support scopes and collections. ( lesser than Couchbase Server  7.0)

You will have to provide a collection name of default as a model option or in global config like below
import { Ottoman } from "ottoman";

const ottoman = new Ottoman({**collectionName: '_default'**});
ottoman.connect(........)

**Comment by sm2017** [comment]
@AV25242 As the ottoman is in alpha I'm worry to use it, I want to use Node.JS SDK

**Comment by AV25242** [comment]
Hello @sm2017  any specific reason you are not comfortable. 
Although we are in alpha we are actively finding and solving issues.
Also, this is going to be both community and officially supported product, you should feel more comfortable. 
There may not be all features that you need thats in there but there are alternatives and intentions to make them available if the right request.

The whole team is here to help and support you.

**Comment by sm2017** [comment]
@AV25242 As I have no time for waiting features, I prefer use stable SDK
Thank you
