### ISSUE TITLE
Ottoman errors are more Generic

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#393]
Ottoman errors are more Generic, this needs to be changed to be specific to the error.
For instance a ValidationError  should provide  be raised as ValidationError instead its raised as an Error.

That was just an example, please find out other avenues where error could be more specific.

**Comment by AV25242** [comment]
@gsi-ariam  one other example is 

When dropping scope that does not exists, it simply throws failed to drop scope. Could it have better feedback, such as scope exist. I see in the API, it seem like it should throw ScopeNotFound error?   

Same thing for Collection

**Comment by AV25242** [comment]
The above needs to be fixed as well just a FYI

**Comment by httpJunkie** [comment]
Blocked by:
https://github.com/couchbaselabs/node-ottoman/issues/423

and on joseph's issue:
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/41
