### ISSUE TITLE
Most of the time bucket unable to connect - Error: cluster object was closed

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#399]
I am facing issue on ottoman connection establishment. sometime working and sometime suddenly throw same error for long time, configured on correct username/password.

(node:28112) UnhandledPromiseRejectionWarning: Error: cluster object was closed
    at Connection.close (D:\API\node_modules\couchbase\lib\connection.js:266:24)
    at conn.connect.catch (D:\API\node_modules\couchbase\lib\cluster.js:612:14)
(node:28112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This is my app.js
------------------------------------------------------------------------
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var indexRouter = require('./routes/index');
var departmentsRouter = require('./routes/departments');

const {ottomanConnection}= require('./database/dbConnection.js');
ottomanConnection.start();

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/api/departments', departmentsRouter);

app.use(function(req, res, next) {
  next(createError(404));
});

**dbConnection file**
--------------------------------------------------------------

var {Ottoman} = require('ottoman');
const dbConfig = require('../config/database.js');
const ottoman = new Ottoman({collectionName: '_default'});
ottoman.connect({
      connectionString: dbConfig.host,
      bucketName: dbConfig.bucketName,
      username: dbConfig.userName,
      password: dbConfig.password,
});
module.exports = {ottomanConnection:ottoman};

-----------------------------------------
i am mentioned in correct username / password, but throws error, anyone help me and advice :)

Thanks in advance

**Comment by gsi-alejandro** [comment]
hi @rajasekar-mu everything seems to be ok.

try to use the `start` function this way to ensure database connection before start the webserver:
`ottomanConnection.start()
   .then(() => app.listen() );`
  
 if the error persists please provide the Couchbase Server version and Ottoman version.
 
  Cheers!

**Comment by rajasekar-mu** [comment]
Hi @gsi-alejandro , thanks for the reply.
i have changed the above options for before start webserver, but still same issue :)
Couchbase server version - 6.5.1
Ottoman version - 2.0.0-alpha.16.2

**Comment by bwgjoseph** [comment]
Does your `bucketName` that you provide already exist in Couchbase? I noticed this error will be thrown when it doesn't exist, and you try to connect to it, and perform operation on it

**Comment by rajasekar-mu** [comment]
Hi @bwgjoseph , yes bucket name exist. sometime working and most of time throw this error

(node:14688) UnhandledPromiseRejectionWarning: Error: cluster object was closed
    at Connection.close (D:\API\node_modules\ottoman\node_modules\couchbase\lib\connection.js:266:24)
    at conn.connect.catch (D:\API\node_modules\ottoman\node_modules\couchbase\lib\cluster.js:612:14)
(node:14688) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rajasekar-mu** [comment]
Hey guys,

While using couchbase sdk without Ottoman, its was working and able insert & fetch the documents. When using ottoman module, then throw the error on connection function onwards.

Then there is no problem on database service side.  Any idea, please tell me :)

**Comment by AV25242** [comment]
hi @rajasekar-mu can you point our team to your repo or can you paste your updated code here.  Ottoman is built on top of node.js sdk you should see the same consistency. There is definitely something not configured properly.

**Comment by rajasekar-mu** [comment]
Hi @AV25242, If something not configure means, then how its working on node.js couchbase sdk. I never see connection issue on nodejs couchbase sdk. 

when use ottoman sometimes working and sometime throw error as **cluster object was closed**, atleast you update the some meaningful error message why this was cluster closed? or any background service need to enable etc.. then developer should understand the problem.

below one is my sample repo, please check. Thanks 

https://github.com/rajasekar-mu/express-ottoman

**Comment by AV25242** [comment]
Thanks @rajasekar-mu  we will check and let you know

**Comment by AV25242** [comment]
@rajasekar-mu  i downloaded your repo  

Changed "only the password" and was able to call /add end point (you can see I have created many docs). And was able to call "/" to get the docs you can see that as well.



![Screen Shot 2021-02-20 at 2 10 44 PM](https://user-images.githubusercontent.com/5351738/108607484-51326080-7386-11eb-8b33-a545fdbb3365.jpg)


![Screen Shot 2021-02-20 at 2 11 12 PM](https://user-images.githubusercontent.com/5351738/108607475-47106200-7386-11eb-835a-09ad24b2a851.jpg)

The only difference is I am using enterprise edition 6.6.1, can you upgrade to 6.6.1 ?  Are you using Community Edition or EE ?

**Comment by AV25242** [comment]
Created few more, after 10 minutes idle time and it works 

`{"status":200,"data":[{"_type":"Departments","change_status":0,"id":"a7614515-aa77-4f8e-8c10-f44129293874","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"cfa4c4fb-1ea0-48a9-9170-64c3f16c851b","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"d7774777-3c39-4d47-9e8a-6121f8c0c636","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"3bdc0fb5-8179-464f-afee-0eb251b09510","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"ed49124d-f2c2-48b0-b4d9-3f17729288df","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"60f978f4-a779-405d-97eb-c5d108a252b9","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"92f98a89-5b6a-48cf-85dd-f91e5cc138f0","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"e28a3b06-6de4-4056-8776-0c3a68f55ba7","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"db479a67-e7c9-4e44-9b35-1a03e7ea9970","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"81710dfa-53c8-41aa-9496-fb9693a9eaf0","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"eeb2f2cd-b93d-41da-b6c7-e81f8628a7ea","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"e66b2b5e-375d-4d04-8f74-a7836ec01da4","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"9171ec1d-9a22-41d6-9ab0-c64b36bd942c","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"6d07d1f5-c01d-4c88-9d0f-31f6ed38106d","name":"Help","status":1},{"_type":"Departments","change_status":0,"id":"f9c70cee-aa1b-4e22-81de-1a07854a49d9","name":"Help","status":1}]}`

**Comment by AV25242** [comment]
Let me know if i need to do something different to recreate the issue ? 

Right now I am calling the add and get as per your readme.md

![Screen Shot 2021-02-20 at 2 32 05 PM](https://user-images.githubusercontent.com/5351738/108607836-71fbb580-7388-11eb-81ec-cdf8c5f69fbd.jpg)

**Comment by rajasekar-mu** [comment]
Hi @AV25242 Thanks for your quick update and testing.

Please find my issue scenario, 

Fresh bucket starting time it was working, we inserted the some documents after changing the schema & update the documents and restart the api service, throw the Error: cluster object was closed.

(node:17856) UnhandledPromiseRejectionWarning: Error: cluster object was closed
    at Connection.close (D:\API\node_modules\ottoman\node_modules\couchbase\lib\connection.js:266:24)
    at conn.connect.catch (D:\API\node_modules\ottoman\node_modules\couchbase\lib\cluster.js:612:14)

_System Info:_
Os: Windows 10,
CouchBase server: 6.5.1 Enterprise Edition

**Comment by AV25242** [comment]
@rajasekar-mu  can you drop the bucket and start over fresh and see if you have the issue ? 
Are you on docker or local install  of couchbase ?

**Comment by rajasekar-mu** [comment]
Hi @AV25242 , i dropped the current bucket and create fresh bucket, seems same issue again something strange. I am tried in local installed couchbase server. 

So now i tried on another option as my demo couchbase server and get below error,

at _getWrappedErr (D:\node\API\node_modules\couchbase\lib\errors.js:816:14)
at Object.wrapLcbErr (D:\node\API\node_modules\couchbase\lib\errors.js:1009:20) at D:\node\API\node_modules\couchbase\lib\collection.js:572:24 {
cause: LibcouchbaseError { code: 201 },
context: KeyValueErrorContext {
status_code: 4,
opaque: 0,
cas: CbCas { ‘0’: <Buffer 00 00 00 00 00 00 00 00> },
key: ‘airline_88331’,
bucket: ‘DataSystems’,
collection: ‘’,
scope: ‘’,
context: ‘’,
ref: ‘’
}

Thanks

**Comment by AV25242** [comment]
Hi @rajasekar-mu  is this the same code base ?  or can you share the new code ?

**Comment by rajasekar-mu** [comment]
@AV25242 below error were get from node js sdk on basic data insert. Previously i tried my local machine now i tried on demo servers at follow server configurations
4 - data node, 2- index node, 2 - query node

at _getWrappedErr (D:\node\API\node_modules\couchbase\lib\errors.js:816:14)
at Object.wrapLcbErr (D:\node\API\node_modules\couchbase\lib\errors.js:1009:20) at D:\node\API\node_modules\couchbase\lib\collection.js:572:24 {
cause: LibcouchbaseError { code: 201 },
context: KeyValueErrorContext {
status_code: 4,
opaque: 0,

**Comment by rajasekar-mu** [comment]
@AV25242 Please find completed error logs on debug mode in Ottoman, 

 couchnode:lcb:info (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:503) Version=3.0.7-njs, Changeset=d2d3666e269b41413408aaae96eb289f1cb4f8ec +0ms
  couchnode:lcb:info (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:504) Effective connection string: couchbase://localhost/StoreOperations?client_string=couchnode%2F3.1.1%20(node%2F10.17.0%3B%20v8%2F6.8.275.32-node.54%3B%20ssl%2F1.1.1d). Bucket=StoreOperations +2ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:372) Applying initial cntl client_string=couchnode/3.1.1 (node/10.17.0; v8/6.8.275.32-node.54; ssl/1.1.1d) +0ms
  couchnode:lcb:info (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:195) DNS SRV lookup failed: LCB_ERR_UNKNOWN_HOST (1049). Ignore this if not relying on DNS SRV records +956ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:138) Adding host localhost:8091 to initial HTTP bootstrap list +956ms
  couchnode:lcb:debug (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:138) Adding host localhost:11210 to initial CCCP bootstrap list +2ms
  couchnode:lcb:trace (instance @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\instance.cc:176) Bootstrap hosts loaded (cccp:1, http:1) +0ms
  couchnode:lcb:info (bootstrap @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bootstrap.cc:270) Requested network configuration: heuristic +40ms  couchnode:lcb:debug (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:94) Preparing providers (this may be called multiple times) +38ms
  couchnode:lcb:debug (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:100) Provider CCCP is ENABLED +2ms
  couchnode:lcb:debug (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:100) Provider HTTP is ENABLED +3ms
  couchnode:lcb:trace (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:314) Refreshing current cluster map (bucket: StoreOperations) +43ms
  express:router:route new '/' +5s
  express:application set "port" to 3000 +8ms
  couchnode:lcb:trace (confmon @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\confmon.cc:300) Attempting to retrieve cluster map via CCCP +3s
  couchnode:lcb:info (cccp @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bucketconfig\bc_cccp.cc:176) Requesting connection to node localhost:11210 for CCCP configuration +3s
  couchnode:lcb:debug (lcbio_mgr @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\manager.cc:501) <localhost:11210> (HE=00000185F3F80DA0) Creating new connection because none are available in the pool +3s
  couchnode:lcb:trace (lcbio_mgr @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\manager.cc:413) <localhost:11210> (HE=00000185F3F80DA0) New pool entry: I=00000185F3E750A0 +4ms
  couchnode:lcb:info (connection @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\connect.cc:485) <localhost:11210> (SOCK=59e78071713d42a4) Starting. Timeout=2000000us +2ms
  couchnode:lcb:error (bootstrap @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\bootstrap.cc:198) Failed to bootstrap client=00000185F3CDE2C0. Error=LCB_ERR_TIMEOUT (201) (Last=LCB_ERR_TIMEOUT (201)), Message=Failed to bootstrap in time +0ms
  couchnode failed to connect to bucket: { [Error: LCB_ERR_TIMEOUT (201): The request was not completed by the user-defined timeout] code: 201 } +0ms
(node:4908) UnhandledPromiseRejectionWarning: Error: cluster object was closed
    at Connection.close (D:\API\node_modules\ottoman\node_modules\couchbase\lib\connection.js:266:24)
    at conn.connect.catch (D:\API\node_modules\ottoman\node_modules\couchbase\lib\cluster.js:612:14)
(node:4908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
  couchnode:lcb:debug (lcbio_mgr @ C:\Jenkins\workspace\nodejs\couchnode\couchnode-scripted-build-pipeline\couchnode\deps\lcb\src\lcbio\manager.cc:523) <localhost:11210> (HE=00000185F3F80DA0) Request=00000185F3E754C0 has no connection.. yet +590ms

**Comment by AV25242** [comment]
@rajasekar-mu  can you change localhost to 127.0.0.1 and try once ?

**Comment by rajasekar-mu** [comment]
After changing localhost to 127.0.0.1, still same issue @AV25242

**Comment by AV25242** [comment]
Hello @rajasekar-mu  thats a bummer, was hoping some results :(, ok so our team is going to do the setup on a windows 10 machine like yours and are going to use this repo : https://github.com/rajasekar-mu/express-ottoman
has anything else changed or anything they need to know. 
If we are not able to reproduce this, probably will jump on a zoom call with you if thats ok for you ?

**Comment by rajasekar-mu** [comment]
Thanks @AV25242 , Please try same repo. if not reproduce the issue, i'm happy to join the call :)

**Comment by rajasekar-mu** [comment]
Issue resolved at new version 2.2.0

**Comment by dbdrop** [comment]
> Issue resolved at new version 2.2.0

Any idea what the core issue is?  I'm seeing the same problem with a connection using the PHP driver.
