### ISSUE TITLE
Query builder results not getting on $in operator

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#424]
Hi ,

I tried with below query builder operations ,

let params = {where: {$in: { search_expr: 'id', target_expr: ["a3827bf5-ea3f-4c56-ae8d-542b23e77213", "155f1772-c671-4703-8bdc-d379d4c4ba47"] }} }
const query = new Query(params, 'StoresPPE').select([{ $field: 'name' }]).limit(10).build();
console.log(query,'---');

Result:
SELECT name FROM `StoresPPE` WHERE id IN ["a3827bf5-ea3f-4c56-ae8d-542b23e77213","155f1772-c671-4703-8bdc-d379d4c4ba47"] LIMIT 10

Getting raw query only, how we fetch the documents? anything i missed

Thanks,

**Comment by AV25242** [comment]
Hello @rajasekar-mu what you are doing is just building the query, to execute the query you will call
ottoman.query(<query>)

see the example here
https://v2.ottomanjs.com/classes/ottoman.html#query

Hope this helps !

**Comment by rajasekar-mu** [comment]
Great Thanks @AV25242 ,

One more doubt we stuck on long days, please guide me,

we stored this key values “device_visibility”:[1,2,3,4,5,6], i want to match device_visibility field to satisfy 2, i tried below option but not working, 

await Model.find({$and:[{status:1},{$in: { search_expr: ‘device_visibility’, target_expr: 2 }}]});

is it correct for $in operator or need to use other operator

**Comment by AV25242** [comment]
I responded back here https://forums.couchbase.com/t/ottoman-v2-logical-where-in-operations-for-array-fields/29880/6

**Comment by rajasekar-mu** [comment]
Thanks , i will follow up forums
