### ISSUE TITLE
Create Many - Extension

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#461]
When using Create Many to create multiple documents, as a user it is difficult to know what documents got created.

Extend Create Many API to 

         a) Allow user to pass in an option that indicates a detailed output is requested  something like detail:true 
         b)  When the above option is set, return back the created documents (or the keys if returning back documents is not possible)
        
In addition to the above, ensure that upon a failure a user should know what failed, probably return back the failed document so that the user can take further actions, just showing how many failed is not enough.

See https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/68 for more information

**Comment by gsi-alejandro** [comment]
We already added the `data` property inside `message` to return an array of the created documents:

Examples
console.log(result) will show this:
![image](https://user-images.githubusercontent.com/15661442/118704979-ac3ced80-b7e5-11eb-87e9-3907871c29ba.png)

console.log(result.message.data) will show this:
![image](https://user-images.githubusercontent.com/15661442/118705115-d5f61480-b7e5-11eb-9c50-b13be9fabcf3.png)

**Comment by AV25242** [comment]
on a failure do you also return back the the failed documents ?

**Comment by gsi-alejandro** [comment]
yes, the ones who fail will be returned back in the `errors`
