### ISSUE TITLE
Investigation - Update Many - Extension

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#462]
When using Update Many to modify multiple documents, as a user it is difficult to know what documents got updated.

Extend Modify Many API to 

         a) Allow user to pass in an option that indicates a detailed output is requested  something like detail:true 
         b) When the above option is set, return back the modified documents (or the keys if returning back documents is not possible)
        
In addition to the above, ensure that upon a failure a user should know what failed, probably return back the failed document so that the user can take further actions, just showing how many failed is not enough.

See https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/68 for more information

**Comment by gsi-alejandro** [comment]
We already added the `data` property inside `message` to return an array of the created documents:

Examples
console.log(result) will show this:
![image](https://user-images.githubusercontent.com/15661442/118705450-3dac5f80-b7e6-11eb-8a12-240c8f9da669.png)

console.log(result.message.data) will show this:
![image](https://user-images.githubusercontent.com/15661442/118705617-72201b80-b7e6-11eb-9e5b-a20f01fc3bcf.png)

Note: `data` will store the success document updated
