### ISSUE TITLE
Investigate - Remove Many - Extensions

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#463]
When using RemoveMany to delete multiple documents, as a user it is difficult to know what documents got deleted.

Extend removeMany API to 

         a) Allow user to pass in an option that indicates a detailed output is requested  something like detail:true 
         b) When the above option is set, return back the deleted documents (or the keys if returning back documents is not possible)
        
In addition to the above, ensure that upon a failure a user should know what failed, probably return back the failed document so that the user can take further actions, just showing how many failed is not enough.

See https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/68 for more information

**Comment by gsi-alejandro** [comment]
We already added the `data` property inside `message` to return an array of the removed ids:
![image](https://user-images.githubusercontent.com/15661442/118712929-5cfbba80-b7ef-11eb-8dcc-e176d42dbe68.png)
