### ISSUE TITLE
standardize searchConsistency

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#464]
looks like the option names are not consistent 

https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/77

**Comment by AV25242** [comment]
Looks like the attribute "consistency" is not being used everywhere.

**Comment by httpJunkie** [comment]
We need to go over this issue and decide what exactly we want to do. Needs more discussion from the team.

**Comment by gsi-ariam** [comment]
@AV25242 @httpJunkie  `consistency`  is proper to `Ottoman` and `scanConsistency` belongs to `coucbhase` the enumerated ones are different,  `consistency` is converted to `scanConsistency` in `Ottoman` this is how version 1 was, hence when using 
`js
cluster.query (query , {scanConsistency: 'request_plus'})
 `
the **couchbase _cluster_** is being accessed which uses `scanConsistency` as an option
