### ISSUE TITLE
findOneAndUpdate is not working 

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#468]
https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/73

**Comment by AV25242** [comment]
Can someone please update what was fixed or what the problem was ?

**Comment by gsi-ariam** [comment]
the document was not saving when the `new` option was false, it was fixed and will be available in the new release

**Comment by AV25242** [comment]
Seems like this is still not working can you please check @gsi-alejandro / @gsi-ariam

**Comment by gsi-ariam** [comment]
**_findOneAndUpdate_** works properly, please check this:

https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/73#issuecomment-846037521
