### ISSUE TITLE
Export ModelOptions

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#475]
Similar to #62, importing ModelOptions is only via (currently)

import { ModelOptions } from 'ottoman/lib/types/model/interfaces/create-model.interface';

**Comment by AV25242** [comment]
Will be fixed with next release

**Comment by gsi-alejandro** [comment]
I already created a [PR](https://github.com/couchbaselabs/node-ottoman/pull/488) to fix it.
