### ISSUE TITLE
Upgrade Ottoman project reference to use couchbase@3.2 

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#485]
https://www.npmjs.com/package/couchbase

Lets get this done for our next alpha release

**Comment by gsi-alejandro** [comment]
It's no possible, due to the couchbase@3.2-alpha version only work with the internal Couchbase Server build.

**Comment by gsi-alejandro** [comment]
Couchbase 3.2 reach a stable version now we going to update Ottoman to use it.

The type system will improve a lot after this enhancement
