### ISSUE TITLE
findOne throw an error at 2.0.0-beta.1 version

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#490]
I expect some features on our latest 2.0.0-beta.1 version, but its throw an error on existing modules. Previously it was working 2.0.0-alpha.16.2. 

If there is an exception/wrong on query side, that time throw error is good. Find a document if document not found its throw an error, this happening on current version.

Current version - create-model.js :
_a.findOne = (filter = {}, options = {}) => __awaiter(void 0, void 0, void 0, function* () {
          const response = yield handler_1.find(metadata)(filter, Object.assign(Object.assign({}, options), { limit: 1 }));
          if (response.hasOwnProperty('rows') && response.rows.length > 0) {
              return response.rows[0];
          }
          **throw new couchbase_1.default.DocumentNotFoundError();**
      })

Old version:
    _a.findOne = (filter = {}, options = {}) => __awaiter(void 0, void 0, void 0, function* () {
        const response = yield handler_1.find(metadata)(filter, Object.assign(Object.assign({}, options), { limit: 1 }));
        if (response.hasOwnProperty('rows') && response.rows.length > 0) {
            return response.rows[0];
        }
        return null;
    })

Can you please change the exception DocumentNotFoundError to null. We are used 2.0.0-alpha.16.2 versions, so what are modules you changed in recent release. When you provide stable release?

**Comment by AV25242** [comment]
Hello @rajasekar-mu yes that was added intentionally and that is something that most of our customer have asked as well. In this case getting more is not a problem, you can wrap a catch around this specific exception and ignore it.

**Comment by rajasekar-mu** [comment]
@AV25242 I'm using multiple findOne function for single api, so need to handle to more try/catch blocks, in that case to increase the code size.

Previously i worked many ODM frameworks, ex: mongoose. Mongoose findOne option is data found then return data, otherwise return null/empty array. This option is common for all programming/ODM frameworks.

I know the catch blocks, but it depend one findOne to another findOne function, in that case code size is increasing, need to write more catch block. 

Catch block mainly to use any wrong query/join(populate) or other connection error time acceptable. Please refer some standard practice and do it. 

Thanks
