### ISSUE TITLE
Find multiple model objects by ids

### ISSUE THREAD

**Issue by chendu** [couchbaselabs/node-ottoman#491]
Hey Team,

Is there a way to find multiple model objects by ids？

```
await HotelModel.find({ id: { $in: ids } });
```

**Comment by AV25242** [comment]
Hello @chendu i think you are in the right thought process, is it not working ?

**Comment by rajasekar-mu** [comment]
@AV25242 above options not working me too also, please check.

@chendu can you try below query builder option,

const select_param = [{ $field: 'id,name,status' }];
let params = {where: {_type:'hotel',$in: { search_expr: 'id', target_expr: [ids-array] }} }
let raw_query = new Query(params, bucketName).select(select_param).build();
let Hotels = await ottomanConnection.query(raw_query);

**Comment by chendu** [comment]
After digging into the code, this way works for me.
```
const { rows } = await XxxModel.find({
      $in: {
        search_expr: 'id',
        target_expr: ids
      }
    });
    return rows;
```

**Comment by chendu** [comment]
> Hello @chendu i think you are in the right thought process, is it not working ?

this doesn't work, got this error `"Operator not found: $in"`

`"ottoman": "^2.0.0-beta.1",`

**Comment by chendu** [comment]
> select_param

Thanks for the response, I find the same ways work for me.

**Comment by chendu** [comment]
> @AV25242 above options not working me too also, please check.
> 
> @chendu can you try below query builder option,
> 
> const select_param = [{ $field: 'id,name,status' }];
> let params = {where: {_type:'hotel',$in: { search_expr: 'id', target_expr: [ids-array] }} }
> let raw_query = new Query(params, bucketName).select(select_param).build();
> let Hotels = await ottomanConnection.query(raw_query);

Thanks for the response, I find the same ways work for me.

**Comment by chendu** [comment]
To be honest, this find by ids, should be official support by ottoman, I even cannot find the demo to show me to do in this way.

**Comment by AV25242** [comment]
@chendu not sure about officially support. FindById is officially supported like any other methods/

**Comment by chendu** [comment]
> @chendu not sure about officially support. FindById is officially supported like any other methods/

Good to me, just create a private method to expose the findByIds method.
