### ISSUE TITLE
Number format data type like function not working 

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#492]
Hi , 

I am using below search on string data types , it working. But number data types not working.

document:
{"_type":"Devices","id":"57cc2900-b950-409b-ab71-4d588a0db2ec","device_type":"metro","store_number":9911,"created_at":"2021-05-27T17:50:27.968Z","updated_at":"2021-05-28T10:15:19.510Z"}

String search:
filter = { device_type: { $like: 'metr%' } };
let DeviceInfo = await DeviceModel.find(filter)

Number search:
filter = { store_number: { $like: '99%' } }; // without quote throw error, so use quote.
let DeviceInfo = await DeviceModel.find(filter)

Anything wrong in code?. Inside like function number not acceptable. So only using quotes.

**Comment by AV25242** [comment]
@rajasekar-mu  LIKE operator is use to MATCH A STRING with a wildcard expression and not NUMEBRS

**Comment by rajasekar-mu** [comment]
@AV25242  There one option for convert number to string
 TO_STR(store_number)  LIKE '99%'
Any options is available for convert number to string & match the values at ottoman?

**Comment by AV25242** [comment]
@rajasekar-mu  nothing as of now. Need to check how underlying N1QL will behave.

**Comment by rajasekar-mu** [comment]
Thanks @AV25242
