### ISSUE TITLE
updateById doesn't work

### ISSUE THREAD

**Issue by chendu** [couchbaselabs/node-ottoman#494]
Hi,
does anyone meet this problem, the `updateById` doesn't work at all from my sdie.
- no error with DEBUG=* mode
- when retrieving the record directly in couchbase, nothing changed.

I'm following this document https://ottomanjs.com/guides/model.html#updating

`const newHello = await HelloModel.updateById(id, data);`

in my `package.json` using ottoman version `"ottoman": "^2.0.0-beta.1",`

**Comment by AV25242** [comment]
@chendu  can you please share the code

**Comment by chendu** [comment]
Hi @AV25242,

below is the code snapshot.

```
private async updateEventById(id: string, data: any) {
	const event = await this.findEventById(id);
	if (!event) throw new DemoError(EVENT_NOT_FOUND, 'Event not existed');

	const merge = { ...event, ...data };
	delete merge['_hype'];

	const update = await EventModel.updateById(id, merge); // NOT WORK

	console.log(update);// undefined

	return update;
}
```

**Comment by AV25242** [comment]
Hi @chendu  I was out last week, are you still facing this issue ?

**Comment by chendu** [comment]
Hi @AV25242,
will try to verify again.

but one quick question about the ottoman version choice,
we are still using Couchbase `community-5.1.1` version, and couchbase nodejs SDK `2.6.12` version.
What's the latest version of ottoman we can use?

**Comment by chendu** [comment]
Just to make that we are using the right ottoman version?

**Comment by AV25242** [comment]
Hi @chendu glad you asked. Ottoman 2.0 is built on top of SDK 3.x and supports Couchbase Server 6.5 and above.
Would recommend moving to latest release.
