### ISSUE TITLE
Error while creating a Collection

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#499]
refer https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/90

**Comment by gsi-alejandro** [comment]
@AV25242 This error can occur when Ottoman has to create a scope and then a collection in that scope, the error is the result that we are trying to create the collection but the scope is not ready to be used yet, we have no way of knowing when the scope is ready to allow creating collections in the.

**Comment by AV25242** [comment]
hmmm ok, so this is an issue with underlying Nodejs SDK ?
@brett19 can you please assist ?

**Comment by AV25242** [comment]
In today's standup (June 8th 2021) a work around to resolve `Error: failed to create collection` within Ottoman was discussed.
This will be an interim solution till the underlying issue from the server is fixed.
The thought process here is 

      - Provide a configuration (Ottoman Configuration) option with a retryCount defaulted to 3.
      - Within the ottoman.start() method retry for errors where creation of collection fails (makes sure its not failing on collection exists) and if the error occurs do an exponential backoff  retry. 
 
Should the retryCount be capped to a maximum say 10 ? its open for discussion.

The idea behind offering a retryCount is to provide auto healing capability. If this option is not provided i.e if no changes to the code were made in this regard then the only option that an end user has is retry manually or restart application manually.

@brett19 , @httpJunkie, @gsi-alejandro  please add anything that is appropriate.
