### ISSUE TITLE
Operator Usage

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#500]
I was wondering if $in (and maybe some other operator) could further simplify the usage?

// from 
.find({
    $in: {
        search_expr: 'model',
        target_expr: ['767-300F']
        }
}

// to
.find({
	model : {
		$in : ['767-300F']
	}
}
I

**Comment by gsi-ariam** [comment]
Yes they can be modified, but these changes would cause that for previous versions the way to use them would be deprecate, I have to review the other operators a little more thoroughly because I found the `letting` operator that has the similar declaration

**Comment by AV25242** [comment]
Thanks @gsi-ariam  lets hold off , dont make any changes but give your proposal on all operators that will be impacted

**Comment by AV25242** [comment]
@gsi-ariam  please come up with the proposal for the changes

     -  Get a list of operators that will fall in this category, the idea is all operators should be used in the same format and should be easy.
     
     - Get the proposal how you intend to fix this and time it will take
     -

**Comment by gsi-ariam** [comment]
@AV25242 these are the proposal changes:

IN/WITHIN Operator

```typescript
const filter = {
  $and: [
    {
      $any: {
        $expr: [{ $in: { search_expr: 'visibility', target_expr: 'network_visibility' } }],
        $satisfies: { $in: { search_expr: 'visibility', target_expr: [2] } },
      },
    },
    {
      $any: {
        $expr: [{ $in: { search_expr: 'visibility', target_expr: 'network_visibility' } }],
        $satisfies: { visibility: [2] },
      },
    },
  ],
};
```
to
```javascript
const filter = {
  $and: [
    {
      $any: {
        $expr: [{ visibility: { $in: 'network_visibility' } }],
        $satisfies: { visibility: { $in: [2] } },
      },
    },
    {
      $any: {
        $expr: [{ visibility: { $in: 'network_visibility' } }],
        $satisfies: { visibility: [2] },
      },
    },
  ],
};
```

Result:
```sql
(ANY visibility IN network_visibility SATISFIES visibility IN [2] END AND ANY visibility IN network_visibility SATISFIES visibility=[2] END)
```
************************************************************************************
LET operator 

```typescript
export interface ILetExpr {
  key: string;
  value: unknown;
}

// to 

export type LetExprType = Record<string, unknown>;
```

and

```
const letExpr: ILetExpr[] = [
  { key: 'amount_val', value: 10 },
  { key: 'size_val', value: 20 },
];

to

const letExpr: LetExprType = {
  amount_val: 10,
  size_val: 20
};
```

**Comment by bwgjoseph** [comment]
Hi,

May I check what is the difference between

```js
// using $any
$any: {
      $expr: [{ $in: { search_expr: 'search', target_expr: 'address' } }],
      $satisfies: { address: '10' },
},

// vs using $in
$in: { search_expr: 'search', target_expr: ['address'] },
```

which is described in [here](https://ottomanjs.com/guides/query-builder.html#build-a-query-by-using-parameters)

The confusion is that `$in` used in `$any`, `target_expr` accepts a `string` whereas in `$in`, `target_expr` accepts an `array`

And that the proposed changes do not include what the original post mentioned w.r.t to the `$in` operator. Does that mean that it would stay as in? And only `$any` and `$let` changes?

Thanks

**Comment by gsi-alejandro** [comment]
In order to simplify the use of the $in operator, we're going to create also a $notIn operator.

the API will look like this: (the suggested one)
```
.find({
  model : {
    $in : ['767-300F']
  }
}

.find({
  model : {
    $notIn : ['767-300F']
  }
}
```
track implementation progress in this ticket

**Comment by bwgjoseph** [comment]
@gsi-alejandro 

That's really great! Thank you!

But what does that mean for the `$any` API? Would that change, or would that stay the same?

**Comment by gsi-alejandro** [comment]
hi @bwgjoseph 
We will add to the roadmap:
- Simplify $let operator (#525)
- Investigate $any for a formal proposal (RFC), if proceed then we can implement it. (#526 )

of course, you and everyone else are welcome to join it.

Thank you for your valuable feedbacks
Greetings.

**Comment by bwgjoseph** [comment]
Thanks @gsi-alejandro 

Would it be ok to include some examples (or reference to documentation) on how does those `operators` work in the respective issue? I wasn't able to find it in the documentation.

So an example would be [$ignoreCase](https://ottomanjs.com/guides/model.html#use-of-ignorecase) where you give some sample docs, how you would use the operator, and what's the expected output of the result. 

Thanks

**Comment by AV25242** [comment]
@gsi-alejandro  any updates on this ?
