### ISSUE TITLE
Adding Metadata in Ottoman Schema and updating Metadata & TTL

### ISSUE THREAD

**Issue by noiissyboy** [couchbaselabs/node-ottoman#503]
I would like to insert a document along with TTL, and update TTL upon modification, is it posible to add expiration Metadata to Ottoman schema? I couldn't find any such implementaion while searching internet.

**Comment by AV25242** [comment]
Hello @noiissyboy  sorry for the delayed response. Yeah TTL can be added to the Collections via maxExpiry

**Comment by AV25242** [comment]
Did this help ?

**Comment by noiissyboy** [comment]
Hello Arun,

I was asking for Document expiry, can you please help on that?

**Comment by noiissyboy** [comment]
Hello Arun,

I was asking for Document expiry, can you please help on that?

**Comment by AV25242** [comment]
Hello @noiissyboy so when you create a `model` you can specify the maxExpiry or TTL as a `model option`.  This will ensure that any document thats created in the collection will always have an expiry. The expiry is specified in `seconds`

https://ottomanjs.com/interfaces/createmodeloptions.html#optional-maxexpiry

There is no other mechanism currently available to set the document expiry

**Comment by gsi-alejandro** [comment]
hi @noiissyboy 

Ottoman right now support TTL for collection's document this way:

`model('ttl', schema, {maxExpiry: 300})`

we configured ttl collection to store documents for just 5 minutes (300 seconds / 60 = 5 minutes, the value is set in seconds)

This week we're working on this feature and we will improve the documentation to be more explicit and add some examples [Ottoman constructor](https://ottomanjs.com/guides/ottoman.html#ottoman-constructor-options) and  [modelOptions](https://ottomanjs.com/guides/model.html#model-options)

`Update` the maxExpiry value for the collection is not implemented yet, but we will soon document some ways to change the maxExpiry document (this [ticket] (https://github.com/couchbaselabs/node-ottoman/issues/510) was created, you can follow the status if you want to be aware)

**Comment by noiissyboy** [comment]
Hi,
alejandro & Arun
I tried maxExpiry as below but still no change in expiration metadata.

const SessionModel = ottoman.model('Session', SessionSchema, {
collectionName: this.collectionName, maxExpiry: 18000 })
{
"meta": {
    "id": "Session::sess:6gUe_YgB5k5Cp97WssAZZrpaq-UaCps_",
    "rev": "2-168d9980eb9700000000000002000000",
    "expiration": 0,
    "flags": 33554432,
    "type": "json"
  },
  "xattrs": {}
}

**Comment by gsi-alejandro** [comment]
hi @noiissyboy 

**This could be the problem:**
The maxExpiry option is used to create the collection with that configuration, maybe the Session collection already exists therefore the maxExpiry doesn't exist on it.

**Solution:** 
To use the maxExpiry value only can be used when creating the collection. (right now isn't possible update this value, you should drop the collection and create it again in order to set maxExpiry value)

**Improvements will come soon:**
We're working on this for better documentation and trying to provide a way to update the document TTL.
