### ISSUE TITLE
Query using model

### ISSUE THREAD

**Issue by aakshaye** [couchbaselabs/node-ottoman#515]
Hello,

I'm using couchbase 6.0.0 with the latest beta release 2.0.0-beta.1. Querying using a model doesn’t return any data when I do `find()` using a model that is registered as shown here:  [https://ottomanjs.com/guides/model.html#getting-existing-models](url)

If I simply use `const User = model('User', { name: string }); await User.find()`
it will work only on the 1st request and 2nd request onwards it gives the error “model is already registered”.

Any information about the correct usage would be very useful.

Thanks,
Aakshaye

**Comment by AV25242** [comment]
Hello @aakshaye creation of Models should happen only once upon bootstrapping. Based on your error message it looks like the code where models are defined is called twice or somewhere in the code you have 2 models with the same name.

**Comment by aakshaye** [comment]
Hello @AV25242, Thanks for you prompt response. 
To be more specific I'm using the following code:
```
import { getModel, model } from 'ottoman';
const User = getModel('User') || model('User', userSchema);
async function getUsers() {
    const result = await User.find();
}
```

which returns an empty `result.rows` object.

**Comment by aakshaye** [comment]
Hello Arun,

Thanks for your response. I ran the code with the latest release 2.0.0-beta.2 and it seems to be working now.
