### ISSUE TITLE
Difference between FindOptions and IFindOptions

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#516]
Looks like a API mismatch ?? 
Please take a look to see why the definitions are off and if this needs to be fixed ?

https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/99

**Comment by gsi-alejandro** [comment]
the FindOptions populate property type was chanced to PopulateFieldsType , but the IFindOptions wasn't updated, this will be fixed next release
