### ISSUE TITLE
Upgrading v1.0.6 -> 2.0.0-beta.1 - pipe delimiter

### ISSUE THREAD

**Issue by kennyLtv** [couchbaselabs/node-ottoman#521]
We're in the process of upgrading from version 1.0.6 to 2.0.0-beta.1 for our systems and have noticed that a pipe is not an acceptable delimiter in 2.0. I believe a pipe was the default delimiter in 1.0.6 and not dictated by us.

My question is, is it fine to modify the regex to include a pipe as an acceptable value, or is there an underlying reason that ottoman has excluded it from this list?

**Comment by AV25242** [comment]
Hi @kennyLtv  are you talking about the key delimiter ?  Prior to 2.0.0 it was free flowing but that was causing other issues. 
Let me check with the team to see if we can make pipe inclusive. Thanks for checking.

**Comment by AV25242** [comment]
@kennyLtv  I think we an add the pipe delimiter.
