### ISSUE TITLE
Simplify $in operator usage

### ISSUE THREAD

**Issue by gsi-alejandro** [couchbaselabs/node-ottoman#523]
new API:

```
.find({
  model : { $in : ['767-300F'] }
})

.find({
  model : { $notIn : ['767-300F'] }
})
```

add new operator for $in negation flag named it to $notIn or similar.

**Comment by bwgjoseph** [comment]
Would the existing API be taken away or is it still valid even with the new `$in` API introduced

```js
$in: { search_expr: 'search', target_expr: ['address'] }
```

**Comment by gsi-alejandro** [comment]
Hi @bwgjoseph 
The existing API will be removed, in order to keep the API as clean as possible. It's the main idea, but we can discuss it if you want.

**Comment by bwgjoseph** [comment]
I think that's reasonable (to remove the existing API).

As mentioned in https://github.com/couchbaselabs/node-ottoman/issues/500#issuecomment-866899748, it would be great for me (and others) to know how the API works with some sample in the issue

Thanks
