### ISSUE TITLE
Lean - Documentation with Examples

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#539]
In  the recent review of the documentation, reference to `lean` with examples were missing.
Please ensure that they are added to the docs

**Comment by AV25242** [comment]
hello @gsi-alejandro  I see some key points missing in the documentation unless I am not looking at the right place

For instance 

    a) Would be nice to show examples performance improvement with lean: true vs lean: false
    b) Mention features that will NOT work when lean is set to true for example validators will not work (I think).
    
    See this documentation for more examples - https://mongoosejs.com/docs/tutorials/lean.html

**Comment by gsi-ariam** [comment]
a) 
- https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/43#issuecomment-813448147
- https://github.com/bwgjoseph/mongoose-vs-ottoman/issues/43#issuecomment-813460128

b) You can find it here:
https://ottomanjs.com/guides/model.html#use-of-lean:
> Documents have a lot of internal state for change tracking. Enabling the `lean` option tells Ottoman to skip instantiating a full Ottoman Document and just give you the plain old JavaScript object (POJO).
> In Ottoman when `lean` option is enabled we return an object using a spread operator, all methods, hooks, etc. are removed.

**Comment by AV25242** [comment]
@gsi-ariam probably jumping on a call will help address this.
