### ISSUE TITLE
groupBy option not working

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#540]
I have execute below query on group by option, but didn't get grouped app_id, duplicate values are repeated.

let RecentlyUsedApps = await ActivityModel.find({user_id:req.decoded.id},{select:'app_id',groupBy:'app_id',limit:generalConfig.recentlyApp}); 

Result:
[
  _Model { app_id: '8e125ed5-c68a-419f-ae0e-b92237cd615f' },
  _Model { app_id: '29acb043-41e6-462a-9597-e3179ab08295' },
  _Model { app_id: '29acb043-41e6-462a-9597-e3179ab08295' }
] 

Thanks

**Comment by gsi-alejandro** [comment]
hi @rajasekar-mu 

[findOptions](https://ottomanjs.com/classes/findoptions.html) don't have a `groupBy` section

Alternatively, you can build your query using the Query Builder this way:

```
const n1qlQuery = new Query({}, 'bucketName')
      .select('app_id')
      .where({user_id:req.decoded.id})
      .groupBy([{ expr: 'app_id', as: 'app_id' }])
      .limit(generalConfig.recentlyApp)
      .build();

console.log(n1qlQuery) // you can print the N1QL query if you want to know exactly what will be executed.

const result = await ottoman.query(n1qlQuery);
```

Cheers

**Comment by rajasekar-mu** [comment]
Thank you @gsi-alejandro 👍
