### ISSUE TITLE
Positional / Named parameter option supporting

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#542]
Hi ,

I have execute below query on Positional parameter and Name parameter on couchbase sdk, it working. But ottoman module not working Positional / Named parameter options.

My doubts ottoman is supporting these option or not, if else what other option we can do.

Ex:
_const query = `SELECT airportname, city FROM \`travel-sample\` 
    WHERE type=$1 
      AND city=$2
  `;
  const options = { parameters: ['airport', 'San Jose'] }_

let result = await cluster.query(query, options) // working
let result = await ottomanConnection.query(query, options); // not working

**Comment by gsi-alejandro** [comment]
Hi @rajasekar-mu 

you're right, our `query` method doesn't support options. 
We'll add `queryOptions` for the next release (beta.4 for this week or the next one)

Thank you.

**Comment by rajasekar-mu** [comment]
Super @gsi-alejandro , once added please share the version. we will try. Thanks

**Comment by gsi-alejandro** [comment]
Hi @rajasekar-mu 

ottoman@2.0.0-beta.4 was released with the fix to add [queryOptions](https://ottomanjs.com/interfaces/queryoptions.html) for the [query](https://ottomanjs.com/classes/ottoman.html#query) method.

**Comment by rajasekar-mu** [comment]
Great @gsi-alejandro, it's working perfectly. Thank you :)
