### ISSUE TITLE
https://v2.ottomanjs.com/ is offline?

### ISSUE THREAD

**Issue by ceddybi** [couchbaselabs/node-ottoman#554]

**Comment by ingenthr** [comment]
Looks to be resolved by @brett19 .  Sorry about that.

**Comment by ceddybi** [comment]
@ingenthr @brett19  no it's not

**Comment by ingenthr** [comment]
I checked again just now and the site is coming up for me.  I will admit though that I did have to refresh it, as it failed the first time.  The interesting thing is this is hosted with github pages.

**Comment by ingenthr** [comment]
@brett19: is there a way @ceddybi can easily build the site locally from a clone of the repo, just as a workaround?

**Comment by ceddybi** [comment]
Thank you @ingenthr, the website was moved to https://ottomanjs.com/

**Comment by ceddybi** [comment]
Just update it in the About section
