### ISSUE TITLE
Add support for Couchbase ARRAY, FIRST and EXISTS collecion operators

### ISSUE THREAD

**Issue by ariamF11** [couchbaselabs/node-ottoman#560]
ARRAY [learn more](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/collectionops.html#array)
The ARRAY operator lets you map and filter the elements or attributes of a collection, object, or objects. It evaluates to an array of the operand expression, that satisfies the WHEN clause, if provided.

FIRST [learn more](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/collectionops.html#first)
The FIRST operator enables you to map and filter the elements or attributes of a collection, object, or objects. It evaluates to a single element based on the operand expression that satisfies the WHEN clause, if provided.

EXISTS [learn more](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/collectionops.html#exists)
The EXISTS condition is used in combination with a subquery and is considered to be met if the subquery returns at least one result.

ARRAY/FIRST usage:
```js
{
  $array|$first: {
      $expr: field_expresion,
      $for: [{ soruce_expr: { $in|$within: target_expr }}],
      $when?: [cond_expr],
      as?: alias
    }
  }
}
```

EXISTS usage:
```js
{
  $exists: target_expr
}
```

**Comment by gsi-alejandro** [comment]
we should approve these enhancements proposed by @ariamF11, in order to implement them.
