### ISSUE TITLE
model.query 

### ISSUE THREAD

**Issue by AV25242** [couchbaselabs/node-ottoman#565]
Currently  the query behavior is available at connection / cluster level.

extend the behavior at model level such that the bucket.scope.collection name is automatically inferred from the model name.

This way as a developer can leave the second parameter in the Query object empty
example 
const query = new Query(params, '').build()
should build the query and the from clause should be inferred from the model operating on .

**Comment by gsi-alejandro** [comment]
Proposal:

**1. Model.namespace** 
will return the string "bucketName.scopeName.collectionName"
usage:
`new Query(params, User.namespace)`

**2. Model.query(params)**
will return a Query instance scoped to the Model  (internally will do `new Query(params, Model.namespace)`)

**3. Add `execute` method to Query class**
usage:
`new Query(...).execute()`
will execute the N1QL query and return a promise with the result.
