### ISSUE TITLE
ECONNRESET occurs often on couchbase 7 community edition

### ISSUE THREAD

**Issue by noiissyboy** [couchbaselabs/node-ottoman#570]
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)

often getting the above error message while trying to update a field, using couchbase 3.2.0 with ottoman 2.0.0-beta.7,  running couchbase 7 community on docker. I had to refresh the ui on browser to get this solved.

**Comment by AV25242** [comment]
Is this a UI issue ?

**Comment by noiissyboy** [comment]
I dont think so, 

Error: read ECONNRESET    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -4077,
  code: 'ESOCKET',
  syscall: 'read',
  command: 'CONN'
}
kindly let me know the meaning of error no -4077

**Comment by AV25242** [comment]
Is this still an issue ? if so please open a follow-up issue with more details.
