### ISSUE TITLE
strict tag can be used on updateById?

### ISSUE THREAD

**Issue by noiissyboy** [couchbaselabs/node-ottoman#571]
Iam creating documents on strict mode but wanted to eleminate some fields on pre save, but when i access the model its expecting to have the eleminated field, below syntax doesnt help either, what could be the possible solution for temporary data which should be validated but not saved in doc?
UserModel.updateById(user.id, { verifiedAt: new Date() }, { strict: false })

**Comment by AV25242** [comment]
hi @noiissyboy not clear with your example, can you please elaborate ?
