### ISSUE TITLE
ModelInstance.fromData() does not work

### ISSUE THREAD

**Issue by ryanlward** [couchbaselabs/node-ottoman#59]
As far as I can tell, using this like a constructor is not supported syntax. Rather than new this(md), I believe it should be new ModelInstance(md).

**Comment by brett19** [comment]
Hey @ryanlward,
Neither of these can actually work due to the requirement of actually needing to know the type of the data you are decoding.  You should be able to use Ottoman.toCoo/fromCoo, 
Cheers, Brett
