### ISSUE TITLE
2.0.0.beta to latest 2.0.0 version upgrade not working

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#601]
Hi ,

I have upgrade the ottoman 2.0.0-beta to latest stable 2.0.0 version. After upgrade getting below errors

**Error:**
TypeError: Cannot read property 'query' of undefined
    at D:\sample\express-ottoman-main\node_modules\ottoman\lib\model\index\n1ql\ensure-n1ql-indexes.js:148:27
    at Generator.next (<anonymous>)
    at fulfilled (D:\sample\express-ottoman-main\node_modules\ottoman\lib\model\index\n1ql\ensure-n1ql-indexes.js:5:58)

----------------------------------------

```
DB connection:
var {Ottoman} = require('ottoman');
const dbConfig = require('../config/database.js');
const ottoman = new Ottoman({collectionName: '_default'});
ottoman.connect({
      connectionString: dbConfig.host,
      bucketName: dbConfig.bucketName,
      username: dbConfig.userName,
      password: dbConfig.password,
});
module.exports = {ottomanConnection:ottoman};
----------------------
app.js:
const {ottomanConnection}= require('../database/dbConnection.js');
const main = async () => {
  try {
       var port = normalizePort(process.env.PORT || '3000');
	app.set('port', port);
        await ottomanConnection.start();
        server.listen(port, () => {
          console.log(`started at http://localhost:${port}`);
        });
  } catch (e) {
    console.log(e)
  }
}
------------------------
Model:
var { ottomanConnection } = require('../database/dbConnection.js');
var DepartmentModel = ottomanConnection.model('Departments', {
	name:String,	
    status:Number,
    sequence:Number,
    seq_status: Number,
    change_status : Number,
    created_at: Date,
    updated_at: Date,
    updated_by: {type:String,ref:'Users'}
},{strict:false});

module.exports={DepartmentModel};
```

**Comment by AV25242** [comment]
Hi @rajasekar-mu  thanks for reaching out, that sounds correct. Its because starting Beta.9.0 connect method became async.

See below the getting started page
https://ottomanjs.com/#getting-started

**Comment by rajasekar-mu** [comment]
Thanks @AV25242 , after i have change the async method in connect area as well, then its working.
