### ISSUE TITLE
How do I interact with views?

### ISSUE THREAD

**Issue by danhab99** [couchbaselabs/node-ottoman#613]
I'm migrating a project from MongoDB+Mongoose to CouchDB+Ottoman but there are some features I'm not sure if are missing.

* I have a `post` model and a `comment` models that include the ID of a `post`. In mongoose I defined a virtual field to count these `comment`s. I know CouchDB has views just like any database but I can't figure out how to interact with them through Ottoman. Any guides or documentation? 

* I also use virtual fields to populate a `post`s `comment`s but I can't find any mention of "populating" in the Ottoman docs. Can we do cross-schema populating with Ottoman the same way as I did with Mongoose?

**Comment by AV25242** [comment]
Hello @danhab99  sorry for the delayed response.

 - [Views are deprecated and will eventually be removed](https://docs.couchbase.com/server/current/learn/views/views-intro.html), so we don't encourage usage of Views.  Can you write a N1QL Query or create an Ottoman pre-hook to accomplish what you need ? 
 
- Yes Ottoman supports ref and populate. You can find it in our  [documentation](https://ottomanjs.com/advanced/ottoman.html#populatemaxdeep-option)

**Comment by AV25242** [comment]
Hello @danhab99  sorry for the delayed response.

 - [Views are deprecated and will eventually be removed](https://docs.couchbase.com/server/current/learn/views/views-intro.html), so we don't encourage usage of Views.  Can you write a N1QL Query or create an Ottoman pre-hook to accomplish what you need ? 
 
- Yes Ottoman supports ref and populate. You can find it in our  [documentation](https://ottomanjs.com/advanced/ottoman.html#populatemaxdeep-option)
