### ISSUE TITLE
find and findOne throwing Error - Cannot read property 'QueryScanConsistency' of undefined

### ISSUE THREAD

**Issue by aakshaye** [couchbaselabs/node-ottoman#615]
Hi,

I'm using ottoman 2.0.0 and get the following error when I try to do a simple find() or findOne():

Cannot read property 'QueryScanConsistency' of undefined

Thanks,
Aakshaye

**Comment by AV25242** [comment]
Hello @aakshaye  the API was made consistent across with 2.0 release, you will use the property consistency within find or findOne to get to the scanConsistency see the example below.

`const result = await Message.find({ text: { $isNull: true } }, { consistency: SearchConsistency.LOCAL });`

**Comment by aakshaye** [comment]
Thanks for your response, @AV25242 . Can you please provide an example for usage with Typescript.

I tried using 

`const existingUser = await UserModel.findOne(
    { email: { $eq: email } },
    { consistency: cbConnection.SearchConsistency.LOCAL }
 );`

Got "Cannot read property 'LOCAL' of undefined"

And for this - 
`const existingUser = await UserModel.findOne(
    { email: { $eq: email } },
    { consistency: cbConnection.ottoman.SearchConsistency.LOCAL }
 );`

Got "Cannot read property SearchConsistency of undefined"

Thanks,
Aakshaye

**Comment by AV25242** [comment]
Hello @aakshaye  you can find a lot of tests here 
https://github.com/couchbaselabs/node-ottoman/blob/master/__test__/model-find-projection.spec.ts

testData.ts has the setup - https://github.com/couchbaselabs/node-ottoman/blob/master/__test__/testData.ts

**Comment by aakshaye** [comment]
Thanks for your response again, @AV25242 . Unfortunately, after providing the consistency option, I still get the same error:
Cannot read property 'QueryScanConsistency' of undefined"

Please advise.

Thanks,
Aakshaye

**Comment by AV25242** [comment]
Can you share your codebase ? or share the code snippet ?

**Comment by aakshaye** [comment]
Here is the snippet that's causing the issue:

utils/ottoman.ts
```
export enum SearchConsistency {
    NONE,
    LOCAL,
    GLOBAL,
}

export const consistency = { consistency: SearchConsistency.LOCAL };
```
userData.ts:
`import { consistency } from "../utils/ottoman";`
...
```
const UserModel = getModel("users") || model("users", usersSchema);
const options: FindOptions = { lean: true, ...consistency };
const existingUser = await UserModel.findOne({ email: { $eq: email } }, options);
```

**Comment by ejscribner** [comment]
@aakshaye what happens if you print out the `consistency` and/or `options` variables? I want to be sure this option is being set properly. I believe it should print something like the following: 
```
{ consistency: 1 }
{ lean: true, consistency: 1 }
```

**Comment by aakshaye** [comment]
Hello @ejscribner , thanks for your response. Yes, it does print exactly that.

```
const UserModel = getModel("users") || model("users", usersSchema);
console.log(consistency);
const options: FindOptions = { lean: true, ...consistency };
console.log(options); 
const existingUser = await UserModel.findOne({ email: { $eq: email } }, options);
```

```
{ consistency: 1 }
{ lean: true, consistency: 1 }
```

**Comment by ejscribner** [comment]
If you set it to use `GLOBAL` instead of `LOCAL` does the issue resolve? Just trying to pinpoint exactly where this is failing. Thanks!

**Comment by aakshaye** [comment]
Thanks again for your response, @ejscribner . Setting to either `GLOBAL`, `LOCAL` or `NONE` did not resolve the issue.

**Comment by ejscribner** [comment]
Unfortunately I am not able to reproduce this issue on my end, but I'll keep looking into it and see if I can find anything else. From what I can tell, `couchbase` is undefined in the `find()` handler and therefore setting `QueryScanConsistency` fails. 

A couple of suggestions to try out if you haven't already:
1. Uninstall and re-install Ottoman
    - `npm uninstall ottoman`
    - `npm install ottoman`
2. Ensure your connection to the Couchbase cluster is successful. Are you able to save documents? (https://ottomanjs.com/classes/document.html#save)
3. For debugging purposes, have you tried using the `travel-sample` dataset thats built into Couchbase? This will provide some default documents to experiment with. (https://docs.couchbase.com/server/current/manage/manage-settings/install-sample-buckets.html)
4. Can you tell me where your cluster is hosted? Are you using Couchbase Capella? A local docker instance? 
5. Are you be able to provide a stripped down version of the project that will allow us to reproduce the issue?

Thanks!

**Comment by aakshaye** [comment]
Can you please elaborate on "`couchbase` is undefined in the `find()` handler" ? Is that something in my implementation or ottoman? 

Thanks for these suggestions.

1. I have tried uninstalling and re-installing ottoman and it didn't help.
2. Yes, I can confirm, I'm able to save documents.
3. I haven't tried using the sample dataset for ottoman, but might give it a try later.
4. The couchbase cluster is hosted on AWS. We're using enterprise edition 6.0.0
5. Unfortunately, I cannot do that at this time.

I have been using ottoman since it was in `alpha` and only faced this issue with version 2.0.0.

**Comment by httpJunkie** [comment]
Have you tried pulling down the `try-ottoman-ts` repo and run it against `travel-sample` dataset?

https://github.com/couchbaselabs/try-ottoman-ts

**Comment by httpJunkie** [comment]
The reason I ask is that I know that it works fine. And having a working version of that project could help you to go through your project and ensure things are done in a similar manner and similar syntax.

**Comment by aakshaye** [comment]
Hello @httpJunkie , I can confirm that the `try-ottoman-ts` repo worked for me on my local docker instance of couchbase.

I'm using similar syntax in my project, however, I'm using `fastify`: [https://www.npmjs.com/package/fastify](url) instead of `express`. 

On inspecting the source code for `try-ottoman-ts`, I see that the `consistency` option has not been used and yet the `find` function seems to be working fine. Please let me know if I'm missing something here.

The `ottoman` query builder is what works for me. It's not as concise as `find`, but does the job for me for now.

**Comment by ejscribner** [comment]
The `consistency` option will set itself to the default if not explicitly set. This still requires the `.QueryScanConsistency` option to be set, which is why you got the error even when you weren't explicitly setting consistency.

I really don’t think using Fastify would have an affect on this. I am wondering if there might be something else that is different in your configuration/dependencies? And `find()` is invoked the same way in your project as it is in the `try-ottoman-ts` repo? If I have some free time in the next week I'll see if I can reproduce the issue by switching to use Fastify in `try-ottoman-ts`.

I'm glad you have something that works for the time being, but I'd definitely like to help you get `find()` working because it'll definitely be more efficient in the long run.

**Comment by aakshaye** [comment]
Thanks for your response, @ejscribner .
> I really don’t think using Fastify would have an affect on this. I am wondering if there might be something else that is different in your configuration/dependencies?

I feel `fastify` shouldn't have an effect on this as well. The other libraries that I'm using are pretty standard npm libraries that you would see in most projects.


> And find() is invoked the same way in your project as it is in the try-ottoman-ts repo? 

Yes, find() is invoked in the same way as in `try-ottoman-ts`.


>If I have some free time in the next week I'll see if I can reproduce the issue by switching to use Fastify in try-ottoman-ts.
I'm glad you have something that works for the time being, but I'd definitely like to help you get find() working because it'll definitely be more efficient in the long run.

Thank you, I really appreciate it!

**Comment by aakshaye** [comment]
**UPDATE**
I played around a bit and it seems BOTH `ottoman` and `couchbase` connections need to be invoked in each file that uses `find` and `findOne`. That is what was causing `couchbase` to be undefined in the `find` handler. 
Feel free to close this issue.
Thank you all for your time and suggestions and wish you all Happy Holidays!

**Comment by ejscribner** [comment]
@aakshaye thats great! Glad you were able to sort it out. Happy Holidays to you as well!!
