### ISSUE TITLE
Custom validation messages 

### ISSUE THREAD

**Issue by vizo** [couchbaselabs/node-ottoman#617]
Hey,

is it possible to customize error messages or getting validation error as an object of params to generate custom error message?

**Comment by ejscribner** [comment]
Hey @vizo! Thanks for reaching out about this, apologies for the delayed response-- much of our team was out for the holidays last week.

You can definitely customize the error thrown by a validator. Take a look at the following code from `src/hotels/hotels.model.js` in our [try-ottoman example repo](https://github.com/couchbaselabs/try-ottoman):

```
addValidators({
  phone: (value) => {
    const regex = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/;
    if (value && !value.match(regex)) {
      throw new Error('Phone number is invalid.');
    }
  },
});
```

You can read more about the `ValidationError` class [here](https://ottomanjs.com/classes/validationerror.html) as well. 

I hope this answers your question, and please feel free to respond with any follow ups!!

**Comment by AV25242** [comment]
Hello @vizo  did this help any ?
