### ISSUE TITLE
Array index

### ISSUE THREAD

**Issue by ramiel** [couchbaselabs/node-ottoman#62]
I have a schema like this:

```js
ottoman.model('something', {
    name: {type: 'string'},
    subscriptions: [{
        shop_id: {type: 'string'}
    }]
}, {
    index: {
       
        // findByShop: {
        //     by: 'subscriptions.shop_id',
        //     type: 'n1ql'
        // }
        
    }
});
```

and I want to create an index on the property `shop_id` inside the `subscriptions` array. It should be possible on couchbase but is it possible with ottoman?

**Comment by brett19** [comment]
Hey @ramiel,

```javascript
{
  index: {
    findByShop: {
      by: 'subscriptions[*].shop_id'
    }
  }
}

**Comment by ramiel** [comment]
Doing it I receive an error:
```
[Error: Syntax error in the map function of the view `Plugin$subscriptions[*]::shop_id': SyntaxError: Unexpected token * (line 3:28)]
```

There's nothing more specified.

**Comment by brett19** [comment]
Hey @ramiel,
Sorry, you need to use the N1QL query type (`type: 'n1ql`).
Cheers, Brett

**Comment by ramiel** [comment]
Yes ok, it do not produce an error.
Of course no index has been created because array index are not supported yet. This is the generated query:
```
SELECT META(b).id AS id FROM `store` b WHERE _type='Plugin' AND `subscriptions[*]`.`shop_id`='aab0c492-6f60-4a72-9231-d905121a8cfb'
``` 
But I'm receiving no results while there are documents which should be returned in fact if I put `4` instead of `*` I got a result

**Comment by brett19** [comment]
Hey @ramiel,
Which version of Ottoman.js are you using?  Only the newest supports the star character in a query.  Additionally, Ottoman does currently attempt to generate an index as we have builds that support array indexing.  Keep this in mind when running your code against older clusters which will cause index building to fail on account of this.
Cheers, Brett

**Comment by ramiel** [comment]
HI, I'm using both the latest version of ottoman (^1.0.3) and the version 4.5 (dev preview) of couchbase. Just to say, the query with the star is not working neither directly on couchbase.
In any case I see no index created or a failed. Thank you for the support by the way. If I discover something more I'll tell you.

**Comment by ramiel** [comment]
Looks like these kind of query (with [*]) doesn't work on couchbase 4.5. I don't know with an older version but even on the official n1ql tutorial the syntax ANY IN SATISFIES like in this example.
```
ANY child IN tutorial.children SATISFIES child.age > 10  END
```
If I'm wrong on something please let me know. Otherwise can you reopen this issue?

**Comment by brett19** [comment]
Hey @ramiel ,
You are correct, however if you actually take a look at the CbStoreAdapter, we are doing conversion from the star operator into an ANY, IN, SATISFIES statement:
https://github.com/couchbaselabs/node-ottoman/blob/master/lib/cbstoreadapter.js#L670-L671

We additionally use the same star operator when generating indices, as you can see here:
https://github.com/couchbaselabs/node-ottoman/blob/master/lib/cbstoreadapter.js#L371-L372

Cheers, Brett

**Comment by ramiel** [comment]
Ok, great, so I just have to wait for the next version ;)
