### ISSUE TITLE
Allow use of n1ql functions in Model.find()

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#64]
Right now, when a user uses `model.find`, it eventually builds an n1ql query and executes it.  This query though only supports direct key = value parameters.  It's not presently possible to use any of the built-in n1ql functions with find though.  For example:  to find documents where a particular property's value contains a certain string (not exact equality).

For example, a user might do something like:
`myModel.find({ foo: 'bar' }, { limit: 1 }, myCallback);`

This code is controlled by cbstoreadapter.js in the _buildFilterExprs function, which takes a filter object and builds a set of expressions that can be concatenated into an n1ql string, which is then executed by `CbStoreAdapter.prototype.find`.

In principle it should be pretty easy to extend buildFilterExprs so that it can take arguments corresponding to various n1ql built-ins.

If this design seems OK, one thing I can do is extend this to have keys in filters correspond to functions, with arrays (rather than objects or strings) as values.   Something like this:

`myModel.find({ regexp_contains: ['myField', 'somePattern'] }, { limit: 1 }, myCallback);`

This would be expected to yield the expression `regexp_contains(bucket.myField, 'somePattern')`.

This approach looks like it can easily be extended to the use of any function in n1ql, and the JSON being sent to the `find` function looks pretty straightforward and readable. Some checking would be necessary to make sure the caller provides the right number of arguments, etc.

**Comment by brett19** [comment]
Hey @moxious,
Is there some reason the existing paradigm of using $ would fail here?  For instance, we already have some 'functions' such as: `.find({'myField': {'$contains': 'someItem'}})`.

**Comment by moxious** [comment]
Well -- this could work.   Locally we've done a lot more work with the query builder that's in this code, and I have changed my mind a bit about this.  In general I think ottoman (medium/long-term) needs a fluent api for building n1ql queries.  I'd rescind this, in that really expanding out on this approach is probably not as good of an idea as allocating time on a fluent api for n1ql.

**Comment by gsi-chao** [comment]
In ottoman v2 a powerful n1ql query builder is introduced. You can review the documentation at this link:
https://v2.ottomanjs.com/guides/query-builder.html#using-the-query-builder
