### ISSUE TITLE
Disable key generation

### ISSUE THREAD

**Issue by doceme** [couchbaselabs/node-ottoman#643]
I am working on migrating a project from lounge to ottoman and can't find anything in the ottoman documentation regarding disabling of key generation. I understand the ```keyGenerator``` allows the customization of the prefix and ID is generated automatically. However, I have a document type that uses a different unique string as the ID (not a UUID). The ID is a unique hardware identifier that will never be duplicated. We are using this unique identified as the ID so that document lookups are fast when the hardware ID is known. I need a way to disable key generation for that document type. In lounge, there is a ```generate: false``` flag that can be applied to a field in a schema to disable automatic ID & key generation. Is there a way to disable key generation in ottoman for a specific document type?

**Comment by doceme** [comment]
Sorry for the confusion. It looks like ID generation is disabled if I simply assign the ```id``` field to a document before saving. It would be nice to have a way to disable ID generation for a specific document type so that if the ```id``` field is not set prior to saving, an error will be generated instead of generating the ID automatically using a UUID.

**Comment by gsi-alejandro** [comment]
@doceme thanks for your feedback, I will create a ticket for this, soon will be implemented. 💯

**Comment by doceme** [comment]
Thanks @gsi-alejandro!
