### ISSUE TITLE
Question: Cross-Schema References

### ISSUE THREAD

**Issue by kishmiryan-karlen** [couchbaselabs/node-ottoman#650]
Hello,
I'd like to know how can I cross reference two ottoman schemas?

For example, if I need something like this:

**user.model.ts**
```
import { postSchema } from './post.schema.ts';

export const userSchema = new Schema({ name: String, posts: [postSchema] });
export default model('User', userSchema);
```

**post.model.ts**
```
import { userSchema } from './user.schema.ts';

export const postSchema = new Schema({ content: String, author: userSchema });
export default model('Post', postSchema);
```

Obviously the above won't work because of cross-referencing modules, but how to achieve this kind of relationship between two schemas?

Note:
In ottoman v1, this was possible since instead of schema instances the names of the models were being passed as strings. So, I guess the references were built after all models were ready and there was no issue.

Thanks

**Comment by gsi-alejandro** [comment]
hi @kishmiryan-karlen 

you can write the schemas this way:
```typescript
export const postSchema = new Schema({ content: String, author: { type: String, ref: 'User' }});
export const Post =  model('Post', postSchema);
```

```typescript
export const userSchema = new Schema({name: String, posts: [{type: String, ref: 'Post'}]});
export const User = model('User', userSchema);
```

then you could use them this way:
```typescript
app.post('/post', async (req, res) => {
    const author = new User({name: "Mark Twain"});
    await author.save();
    const post = new Post({content: "Oliver Twist", author: author.id});
    await post.save();
    res.status(200).send(post);
});

app.get('/post', async (req, res) => {
    const posts = await Post.find({}, {populate: '*'});
    res.status(200).send(posts);
});
```

```typescript
app.post('/user', async (req, res) => {
    const post1 = new Post({content: "Harry Potter and the Philosopher's Stone"});
    await post1.save();
    const post2 = new Post({content: "Harry Potter and the Deathly Hallows"});
    await post2.save();
    const author = new User({name: "J. K. Rowling", posts: [post1.id, post2.id]});
    await author.save();
    res.status(200).send(author);
});

app.get('/user', async (req, res) => {
    const users = await User.find({}, {populate: '*'});
    res.status(200).send(users);
});
```

I hope it helps, if you need anything else just let me know,
Best regards.

**Comment by kishmiryan-karlen** [comment]
hey @gsi-alejandro ,

Thanks a lot for your answer and the complete example!

The following is a bit confusing though. Does it mean that `ref` overrides the `type` when both are provided?

`{ type: String, ref: 'User' }`

**Comment by gsi-alejandro** [comment]
hello @kishmiryan-karlen 

`type` will be the value type saved in the Database (string this case, due to User Model's Id being a UUID).
`ref` will create a reference to that Model ("User" in this case).

When you retrieve the documents from DB you can populate them or not. Loading the corresponding documents for each document reference.
