### ISSUE TITLE
unexpected `strict` in the ShemaOptions

### ISSUE THREAD

**Issue by xavierchow** [couchbaselabs/node-ottoman#656]
According to the doc: 
* https://ottomanjs.com/guides/schema.html#schema-options
* https://ottomanjs.com/guides/schema.html#strict-mode

> The strict option (enabled by default) ensures that values passed to our model constructor that were not specified in our schema do not get saved to the database.

it is supposed to be enabled by default. However, it turns out that when specifying a SchemaOptions that doesn't include the `strict` property(e.g. `new Schema({ name: String, age: Number }, { timestamps: true })`, the default becomes false. 
It's misleading and not consistent with the doc.

pointing out the related code as follows,

https://github.com/couchbaselabs/node-ottoman/blob/776253abdf8585ddff08e5f462127a97c5f53752/src/schema/schema.ts#L99-L103

**Comment by xavierchow** [comment]
@gsi-alejandro 

>this line will be changed to:

> const strict = options?.strict === undefined ? false : options.strict;

shouldn't be **true** as the default?
```js
const strict = options?.strict === undefined ? true : options.strict;
```

**Comment by gsi-alejandro** [comment]
Sorry @xavierchow 

I share with you a piece of code with an error, the committed one is correct and will be shipped in the next release.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/15661442/168944967-767fe9d3-d7a4-400a-8f3f-9f2b45e899b5.png">

**Comment by xavierchow** [comment]
@gsi-alejandro thank you for your explanation; looking forward to the next release!

**Comment by AV25242** [comment]
@gsi-alejandro is this done if so please close this issue 

Cc : @thejcfactor
