### ISSUE TITLE
unset option support

### ISSUE THREAD

**Issue by rajasekar-mu** [couchbaselabs/node-ottoman#657]
Hi ,

I need to unset the specific key in model.

ex: {"name":"David","status":1,"grade":"2C"}
expect result to delete the grade key in above document

result: {"name":"David","status":1},

I know UNSET Clause in n1ql, similar option is support Ottoman Model?

Thanks,

**Comment by rajasekar-mu** [comment]
Thanks @gsi-alejandro , 

If we have 30+ keys & subdocuments, its difficult to update replaceById. So could you add this feature.

**Comment by gsi-alejandro** [comment]
hi @rajasekar-mu 

The will discuss this feature request.

I will notify you about the progress.

Best Regards.
