### ISSUE TITLE
Global consistency

### ISSUE THREAD

**Issue by yamsellem** [couchbaselabs/node-ottoman#66]
It seems there ain't no way to globally change the consistency of ottoman requests.
Only one query at a time with `model.find({}, {consistency: ottoman.Consistency.NONE},callback)`

Something like `ottoman.setGlobalConsistency(ottoman.Consistency.NONE)` would be great.

**Comment by brett19** [comment]
Hey @yamsellem,
It is usually considered bad practice to globally require indexes on all your models.  It may make sense to add controls for this on a per-index basis on the model definition though.
Cheers, Brett
