### ISSUE TITLE
Private fields

### ISSUE THREAD

**Issue by ramiel** [couchbaselabs/node-ottoman#67]
The private fields is a great feature but two things are missing I guess:

- Documentation. I can make a PR if needed
- Set as private a property which is an array. Or maybe I do not understand how to do it

It will be possible?

**Comment by brett19** [comment]
Hey @ramiel,
It should be possible, you should be able to do it using the more complex way of defining a field, something like...
```javascript
.model({
  myfield: {type: ['string'], ...}
})
```
Cheers, Brett

**Comment by ramiel** [comment]
Can I do the same on `subscriptions` given subscription defined like this?
```js
subscriptions: [{
    shop_id: {type: 'string'},
    date: {type: 'Date'},
    config: {type: 'Mixed'}
}],
```
