### ISSUE TITLE
npm i on node 18 is too long ( more than 3 minutes )

### ISSUE THREAD

**Issue by Ibrahimtrrc** [couchbaselabs/node-ottoman#680]
hi everyone, 
i found out that when you work with node 18 and npm 8.19, the installation is very very long. 
if we install with the verbose flag, we observe that the node-gyp part is taking more time than previous versions.
Using 
> NodeJS  18.12.0
> NPM 8.19.3
> ottoman 2.2.2 

is it a known behaviour ? 

here is the node-gyp rebuild step and his timing
```console
npm info run couchbase@3.2.6 install node_modules/couchbase prebuild-install || node-gyp rebuild
npm info run couchbase@3.2.6 install { code: 0, signal: null }
npm timing build:run:install:node_modules/couchbase Completed in 178150ms
```

here is the full install timing
```console 
found 0 vulnerabilities
npm timing command:i Completed in 218745ms
npm verb exit 0
npm timing npm Completed in 218910ms
npm info ok 
```

**Comment by gsi-alejandro** [comment]
hi @Ibrahimtrrc 

Thank you for your feedback we are checking it. 

I will keep updating this ticket, hope it's solved soon.

**Comment by AV25242** [comment]
Lino what the update on this  ?

**Comment by thejcfactor** [comment]
Hi @Ibrahimtrrc  -- Can you use an earlier version of Node.js? The 3.x Couchbase Node.js SDK is compatible w/ Node.js 10, 12 and 14.  See compat docs below.

When ottoman updates to using the 4.x Couchbase Node.js SDK, that version of the SDK is compatible with Node.js 12, 14 and 16. 

@gsi-alejandro - It looks like ottoman says it is compatible with Node ^8.0.0.  We should mention the upper limit as well.

- [Couchbase Node.js 3.x SDK Compatibility](https://docs.couchbase.com/nodejs-sdk/3.2/project-docs/compatibility.html)
- [Couchbase Node.js 4.x SDK Compatibility](https://docs.couchbase.com/nodejs-sdk/current/project-docs/compatibility.html)
