### ISSUE TITLE
Defining a model should not need bucket to be open

### ISSUE THREAD

**Issue by yamsellem** [couchbaselabs/node-ottoman#71]
With release 1.0.3, the following code fails:

``` javascript
var ottoman = require('ottoman');
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');

var Furniture = ottoman.model('Furniture', {
  name: 'string'
});

ottoman.bucket = cluster.openBucket('default');
```

With the error:

```
TypeError: Cannot read property 'store' of null
      at node_modules/ottoman/lib/modelinstance.js:442:23
```

The bucket should be open to define a model, so the following code works:

``` javascript
var ottoman = require('ottoman');
var couchbase = require('couchbase');
var cluster = new couchbase.Cluster('couchbase://127.0.0.1');
ottoman.bucket = cluster.openBucket('default');

var Furniture = ottoman.model('Furniture', {
  name: 'string'
});
```

This seems wrong to me, defining a model should not need the bucket to be open.
It defines a contract, it do not need the database to event exist at the time of definition.
It's querying the model (`create`, `update` & co) that should need the bucket, don't you think?

In fact, this cause severe issues & ugly fixes in unit testing.

Thanks for your help.

**Comment by brett19** [comment]
Hey yamsellem,
This is actually a 'feature' in that it is intended to allow you to have models from your application reside in multiple buckets.  It is possible that it may be worth considering changing the behaviour of this to make it simpler to set things up.  I agree that the current way is a bit... terrible.
Cheers, Brett

**Comment by brett19** [comment]
I think I am going to modify this such that each Model maintains a reference to it's parent context (the Ottoman object).  This means we will be able to resolve storage adapters at first-use, rather than registration time.

**Comment by gsi-chao** [comment]
In ottoman v2 it is not necessary to interact directly with the couchbase SDK, the operation of opening the bucket is done automatically, so this operation is transparent for the user. You only need to open a connection and create as many schemas and models as the user needs.
