### ISSUE TITLE
Documentation: we need a search in ottoman documentation

### ISSUE THREAD

**Issue by kayraberktuncer** [couchbaselabs/node-ottoman#712]
I have to go and look at the node_modules when I need something, the document should be searched and we should be able to access it easily.

**Comment by deniswsrosa** [comment]
Hi Kay,

Could you please elaborate a little bit more on your request? We could prioritize that.

**Comment by kayraberktuncer** [comment]
Actually I'm new on ottoman and couchbase. But I have some experience node and databases. In the backend project we created, we use ottoman to go to couchbase. And most of the time I need documentation because I don't know what to use and how to use it, and I have to go through the documentation to find what I'm looking for. It would be more useful if there was a search where I could find what I was looking for directly.

I don't look at any documentation anymore, I'm looking for what I want to do in the comment lines inside the package.

**Comment by ejscribner** [comment]
Hey @kayraberktuncer, thanks for this suggestion! We are now working to add search functionality to our docs site at https://ottomanjs.com/. I will follow up here once it is complete.

**Comment by ejscribner** [comment]
Hey @kayraberktuncer, thanks for your patience on this. We've just deployed a new docs site to https://ottomanjs.com/ complete with search functionality. Feel free to try it out!

**Comment by kayraberktuncer** [comment]
It's great, thanks for your efforts
