### ISSUE TITLE
Ignore undeclared attributes

### ISSUE THREAD

**Issue by yamsellem** [couchbaselabs/node-ottoman#72]
Uncommenting `table.size` in the following code will throw `TypeError: Cannot read property 'type' of null`. Adding a property not defined in the model should be ignored by ottoman, I guess. That's the goal of the fields declaration to me: declare what should be considered by the database and ignore everything else.

```javascript
describe('Ottoman', () => 
    it('should ignore undeclared attributes', function(done) {
        var ottoman = require('ottoman');
        var couchbase = require('couchbase');
        var cluster = new couchbase.Cluster('couchbase://127.0.0.1');
        ottoman.bucket = cluster.openBucket('default');

        var Furniture = ottoman.model('Furniture', {
            name: 'string'
        });

        var table = new Furniture({name: 'table'});
        // table.size = 12;

        table.save(function(err, value) {
            assert.isNull(err);
            done();
        });
```

**Comment by sroccaserra** [comment]
I'm interested in this too !

**Comment by brett19** [comment]
As part of our validation code, we intentionally do not permit extra data be included in objects.  I think it would likely be even more dangerous if we were silently ignoring data that might otherwise have been expected to have been saved.
