### ISSUE TITLE
Save without getting first

### ISSUE THREAD

**Issue by yamsellem** [couchbaselabs/node-ottoman#73]
Is there a way to save a model without getting it first?

The model `_id` is read only, so it seems impossible to create a model with it's id to save it directly.
Thanks.

**Comment by brett19** [comment]
Hey @yamsellem,
It is not possible to save a model without retrieving it first.  This is due to the fact that we must retreived the document to prevent concurrent updates or loss of field data (since an Ottoman.js model instance represents the full set of data in a document).
Cheers, Brett

**Comment by yamsellem** [comment]
@brett19 Ok, that make sens. Thanks.
