### ISSUE TITLE
Defining a custom key

### ISSUE THREAD

**Issue by yamsellem** [couchbaselabs/node-ottoman#74]
Is there a way to define a custom key on model creation?
What are the possibilities available around the document key (field, naming strategy, etc)?

Ottoman's doc got the same issues than couchnode, we've got to read the source every time a question happened. It would be super nice if we didn't (_on the simple cases at least_).

Thanks.

**Comment by erik-etops** [comment]
Yep, if you say 
```
ottoman.model('User', {
    username: { type: 'string' , readonly: true},
...etc..., { id: 'username' }
```
The latest version of ottoman will use this as a natural key for constructing the document key, and for user yamsellem you'll see a document called "User|yamsellem" with the pipe delimiter. Note that you need readonly set to true, and it also can help to have a refdoc index on the field. If you don't specify an id in the 3rd argument of options (where you can also set up indexes) then ottoman automatically uses a uuid generator to make the document keys as a surrogate value. 
Also note that this field should not be null and must be unique across your documents. :)
