### ISSUE TITLE
View query running failed with couchbase sdk 4.2.8

### ISSUE THREAD

**Issue by superbogy** [couchbaselabs/node-ottoman#763]
Hi, we are heavily using view query now. But the Couchbase SDK of ottomanjs  `4.2.8` was wrapped in quotes for the query options like `key` `idRange` etc. Which makes view query always fail. This issue was reported at https://issues.couchbase.com/browse/JSCBC-1214 and fixed in the current Couchbase SDK `4.3.0`. Please update the Couchbase SDK to the latest version to make the view query run correctly in `ottomanjs`. 
Thank you.

**Comment by ejscribner** [comment]
Thanks @superbogy, and sorry for the delayed response! We should have a release in the coming week or two that will bump the underlying Couchbase SDK to latest.
