### ISSUE TITLE
ModelInstance.prototype.load doesn't follow documentation

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#83]
In the code, there is this:

```
/**
 * Loads this object, or sub-objects from this object from the data store.
 * This function can be called while a model instance is already loaded to
 * reload the model instance, or to load specific sub-model-instances.
 *
 * @param {...string=} paths Paths to sub-model-instances to load.
 * @param {Function} callback
 */
ModelInstance.prototype.load = function(callback) {
```

The load function isn't currently able to load by paths as the documentation specifies.  Tests don't seem to rely on this behavior, so maybe it can be removed from the documentation

**Comment by brett19** [comment]
Why do you say that it cannot?  I can see the code for it, and it appears to function properly.
