### ISSUE TITLE
ensureIndices - Operation not supported

### ISSUE THREAD

**Issue by Dev-Dipesh** [couchbaselabs/node-ottoman#84]
Since I'm using Couchbase CE 4.0 (MDS not supported), ensureIndices can not create indices and throws above error. I've read that full homogeneous scaling is possible in CE with all services running on all nodes, but can someone shed more light on how that can be achieved.

This is my current cluster configuration -

![screenshot from 2016-06-03 13 23 34](https://cloud.githubusercontent.com/assets/3931017/15772396/7fd579aa-298e-11e6-962e-06d420ec13c1.png)

and here is a command from Arun Gupta - 
```sh
curl -v http://$ip:8091/node/controller/setupServices -d services=kv%2Cn1ql%2Cindex
```

Though I wonder if I can use both Index and query benefits using it and can also use Ottoman function.

**Comment by brett19** [comment]
Hey.  As long as query is enabled, you should be able to connect and use it (even without MDS).  Additionally, it is intended to be possible to use ottoman without generic finds and not depend on N1QL at all, but its possible that a recent change has broken that capability.
