### ISSUE TITLE
Missing basic _type index 

### ISSUE THREAD

**Issue by moxious** [couchbaselabs/node-ottoman#86]
When ottoman creates n1ql indexes for its model documents, it generally does so like this:

```
CREATE INDEX `MyModel__someField` 
ON `bucketName`(`someField`) 
WHERE _type="MyModel" 
USING GSI WITH {"defer_build": true}
```

This is good and appropriate - but all models then rely on scanning the bucket for all documents where `_type='MyModel'` on n1ql queries, particularly the ones implemented by cbstoreadapter findModels.

There's a basic index on the `_type` attribute itself that's missing.  Without this index, a `PrimaryScan` is necessary in order to do a query like this:

```
explain SELECT META(b).id AS id 
FROM `someBucket` b 
WHERE _type='MyModel' LIMIT 1 OFFSET 0;
```

Without the `_type` index, this query performs extremely poorly since the DB must scan every single document in the entire store until it hits the first one where `_type='MyModel'`.  With a simple index on `_type` this query performs predictably quite well.

Because almost **all** ottoman generated n1ql queries rely on filtering based on `_type` it seems like a no-brainer to add a GSI index to `_type` whenever the user has any GSI indexes at all.

To give an idea of the impact of this sort of thing -- suppose you do `MyModel.find({}, { limit: 1 }, someCallback)` -- locally in a database with 13,000 documents in it, about a dozen models -- with this index the result is about 150ms execution time.  Without the index, query execution is about 3 seconds.

**Comment by brett19** [comment]
Hey @moxious,
This is indeed a change that would be highly beneficial.  I should be able to get this in on Monday.
Cheers, Brett

**Comment by agonyou** [comment]
Question: Have you tried adding "where _type is not null" or can we add it? This will force an index to be used where _type has been indexed.

**Comment by moxious** [comment]
@agonyou haven't tried it, but not quite sure what you mean; right now I'm manually creating the missing index, and performance looks great.  Without this index the performance is pretty poor -- if I were to add to those queries "where _type is not null" that would add another criteria for sure, but the real problem seems to be the PrimaryScan of every document in the DB, and this extra clause doesn't seem to change that.   Am I misunderstanding what you're suggesting?

**Comment by agonyou** [comment]
OH there wasn't an index. I misunderstood. Yes, that's true, if the optimizer doesn't find a satisfying index it will scan against the primary. If you have an index which satisfies the query it can be used in 2 ways. 1. you can add "use index" example: SELECT name, abv FROM `beer-sample` USE INDEX (beer_abv) WHERE abv > 10; This will ensure you use specifically the required index or cause an error that the index doesn't exist. 2. use the "where attribute is not missing" clause so that when you select the optimizer attempts to satisfy the query with the first index which can satisfy or even cover the query completely and bypass any calls to the data nodes (which is part of the pain of the scan) at least until Couchbase 4.5 comes.  Let me know if you need additional syntax. You can also read more here: http://developer.couchbase.com/documentation/server/current/indexes/covering-indexes.html

**Comment by agonyou** [comment]
@moxious After re-reading your initial usage, I would simply add the _type to the index you created, or create a discreet index for _type. It's automatically maintained either way, but the important part here regarding your question is that if you're not specifying which keys to scan yourself, and are asking the query engine to continue the query based on _type you'll see in an explain that there is no satisfying index for _type and therefore it must scan. having an index any index, which includes _type, is about the only way to prevent scanning #primary. Use 'explain' on the query you provided with and without the _type attribute indexed anywhere and I think you'll see what I'm referring to. if there are other attributes than _type that could also be used to filter the query then I suggest creating an index which can cover multiple attributes. Using the 'where attribute is not missing' clause or use index statements will make it easier for the query processor to choose which index to scan, i.e. primary or secondary.  
Does that make sense?

**Comment by moxious** [comment]
That makes sense.   I think this fix is quite simple; in my codebase I have a 1-line workaround that is this:

```
this.runN1ql(`CREATE INDEX \`Ottoman__type\` on \`${config.bucket}\`(\`_type\`) USING GSI;`)
```

Doing basically that fixes the issue, and IMHO if an ottoman user has any GSI indexes, they should have that one.  Because `_type` is Ottoman internal magic, I thought this is inappropriate to be in my code and should be in Ottoman instead.

Indeed using explain is how I found this.

Creating other indexes to cover multiple attributes  is a reasonable idea, the trouble is that ottoman in many cases is generating ad-hoc queries via the findModels function.   So in order to make smart compound indexes, you have to first observe system behavior, figure out which ones are most commonly searched in conjunction with one another.

**Comment by agonyou** [comment]
@moxious Ahh. Yes good deal. I agree. I'm not terribly familiar with Ottoman and I think I understand what it's for in general. if _type is *always* used as you mentioned, I agree that your addition is the way to go, even long-term not so much as a workaround but a preparatory step on first access to ensure it runs properly. 

Memory-optimized-indexes in 4.5 will be awesome for scans, but it's still going to be slower than an index backed query. Using MOI for the _type query will be super fast over and above what you see now. 

Looking forward, I'm curious if in addition to having the index, could using some prepared queries and calling them by name further optimize performance?  Great find @moxious !

**Comment by moxious** [comment]
Submitted PR to fix: https://github.com/couchbaselabs/node-ottoman/pull/90

**Comment by moxious** [comment]
PR was accepted, this is fixed on the latest master.
