### ISSUE TITLE
Driver 2.2.1 error

### ISSUE THREAD

**Issue by ramiel** [couchbaselabs/node-ottoman#96]
With the latest couchbase driver (version 2.2.1) ottoman returns this error any time it tries to do a N1QL query
```
TypeError: First argument needs to be a ViewQuery, SpatialQuery or N1qlQuery.
        at Bucket.query (/node_modules/couchbase/lib/bucket.js:957:11)
        at CbStoreAdapter.find (/node_modules/ottoman/lib/cbstoreadapter.js:752:15)
        at Ottoman._findModels (/node_modules/ottoman/lib/ottoman.js:551:16)
        at Function.ModelInstance.find (/node_modules/ottoman/lib/modelinstance.js:608:23)
        ...
```

If I execute a N1QL query directly this problem is not present and it looks the same code path is executed (on couchbase module I mean).

I tried to change node-ottoman dependency to enforce the latest version of couchbase and your tests pass.
Any idea of what is happening?
Aside, this happens even at the index creation if any.

**Comment by moxious** [comment]
I didn't know that this was possibly related to the newest node driver but I do know what this is about.  It's complicated.

https://forums.couchbase.com/t/typeerror-first-argument-needs-to-be-a-viewquery-spatialquery-or-n1qlquery/8834

**Comment by ramiel** [comment]
Thanks...looks very hard to fix...

**Comment by moxious** [comment]
Are you using es6 at all?  Just curious if this co-occurs with that for you.

**Comment by ramiel** [comment]
I'm using ES6 (on node 5) but I think is not related. I think in my case the inherits problem is due to a strange requiring order (I able to reproduce the error using a pre-instantiated singleton of the db connection while I have no problem with a new instance).

Basically now I know how to fix this behavior in my code, I don't know how to fix the deeper issue.

**Comment by moxious** [comment]
Could you please describe any details you have about how you fixed it in your case?  Might at least be a hint for others.

**Comment by ramiel** [comment]
Yes ,yes. I did not fix yet but if I'll do I'll share it here.
By the way I moved `N1qlQuery` and `N1qlStringQuery` to be two (es6) classes to see if this, as your link suggested, would have solved the problem: the issue is still there!
This seems to suggest that the problem is not related to the `inherits` implementation

**Comment by moxious** [comment]
Perhaps it's not `inherits` but the root of the bug is that `somen1qlStringQuery instanceof N1qlQuery` evaluates to false.  If that weren't the case, then the error would never arise, right?

**Comment by ramiel** [comment]
Exactly. Then your link suggest this is due to node.js `inherits` implementation so I was investigating

**Comment by brett19** [comment]
Hey Guys,
The issue is that the couchnode version that is 'included' in ottoman is not matching the couchnode version that is used in your application.  Due to this, when you instantiate the Couchbase connection object, its 'version' of N1qlQuery does not match the version of N1qlQuery being created by Ottoman.  I am looking into a way to solve this problem on a more general basis, but I have not got an answer as of yet.
Cheers, Brett

**Comment by moxious** [comment]
It is possible that this is related?   Odd problem that cropped up recently with new versions of the couchbase driver working together with ottoman.

```
Connecting to couchbase://couchbase://localhost:8091?detailed_errcodes=1, opening bucket default

/home/ubuntu/db-migrate-couchbase/node_modules/couchbase/lib/bucket.js:167
  this._cb = new CBpp(bucketDsn, bucketUser, bucketPass);
             ^
CouchbaseError: Invalid input/arguments
    at new Bucket (/home/ubuntu/db-migrate-couchbase/node_modules/couchbase/lib/bucket.js:167:14)
    at Cluster.openBucket (/home/ubuntu/db-migrate-couchbase/node_modules/couchbase/lib/cluster.js:137:16)
    at Object.<anonymous> (connection.js:15:24)
    at Module._compile (module.js:413:34)
    at loader (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by brett19** [comment]
This issue has been corrected with newer driver versions, and Ottoman now has a fix that involves simply passing your Couchbase instance to the store adapter when trying to use couchbase cross-version.

**Comment by royrico** [comment]
I have also found that you get this error if you include couchbase in the DSN

produces error
`const cluster = new couchbase.Cluster(`couchbase://${dbServer}`);`

does not produce error  
`const cluster = new couchbase.Cluster(`${dbServer}`);`
  
Adding this here, because this was the highest google search result i found

**Comment by harishasan** [comment]
> I have also found that you get this error if you include couchbase in the DSN
> 
> produces error
> `const cluster = new couchbase.Cluster(`couchbase://${dbServer}`);`
> 
> does not produce error
> `const cluster = new couchbase.Cluster(`${dbServer}`);`
> 
> Adding this here, because this was the highest google search result i found

Saved my life. Thank you
