### ISSUE TITLE
Can't get referenced model to load

### ISSUE THREAD

**Issue by Johnsel** [couchbaselabs/node-ottoman#97]
Possibly this is just me not understanding the docs right, but my model isn't fetching referenced models  automatically. 

All I get is an unloaded reference:
OttomanModel(`Organization`, unloaded, key:Organization|0236c3e8-6ff2-4587-a214-21046b6873ea, {})

The key exists, and according to the docs: http://ottomanjs.com/#toc9 :
_Accessing the data of a referenced document is as simple as requesting the parent document; referenced documents will be loaded by default._

**Comment by brett19** [comment]
Hey @Johnsel,
This appears to be a documentation error.  It should indicate that the referenced models will be instantiated automatically, not that they will be loaded.  You should call .load() on them to load them, or alternative specify them during the loading of the model (by passing its path as a string in the .load call).  For example, for a model with a "org" field which is of type Organization.  You may call myUser.load('org') (note that the parent is always loaded by default).
Cheers, Brett

**Comment by Johnsel** [comment]
Hi Brett, bit of a delay in responding to you, but thanks! That makes sense and I will try it out later today.

**Comment by ryanluton** [comment]
@Johnsel did you figure this out? I ran into the same issue. Although I know I have an async issue along with probably trying to tackle it incorrectly. 

```
//GET api/sites
exports.sites = function( req, res ) {

  site.find( req.query, { sort: 'name' }, function( err, data ) {
    if ( err ) {
      res.status = 400;
      res.send( err );
      return;
    }

    var siteArray = [];

    function loadRefs( done ) {
      for ( var i = 0; i < data.length; i++ ) {
        var s = data[ i ];
        for ( var j = 0; j < s.uploadHistory.length; j++ ) {
          h = s.uploadHistory[ j ];
          h.load( function( err ) {
            if ( err ) {
              res.status = 400;
              res.send( err );
              return;
            }
            siteArray.push( s );
          } )
        }
      }
      done();
    };

    loadRefs( function() {
      res.send( siteArray );
    } );

  } );
```

**Comment by brett19** [comment]
Hey @ryanluton,
Something like the following should work for your case:
```javascript
  site.find( req.query, { sort: 'name', load: ['uploadHistory'] }, function( err, data ) {
    if ( err ) {
      res.status = 400;
      res.send( err );
      return;
    }

    res.send(data);
```
Cheers, Brett

**Comment by ryanluton** [comment]
Exactly what I needed, and much simpler! Thanks much @brett19
